local M = {

 [0x000] = {{stat="none",offset=0}},
 [0x001] = {{stat="HP", offset=1}},
 [0x002] = {{stat="HP", offset=33}},
 [0x003] = {{stat="HP", offset=65}},
 [0x004] = {{stat="HP", offset=97}},
 [0x005] = {{stat="HP", offset=1,multiplier=-1}},
 [0x006] = {{stat="HP", offset=33,multiplier=-1}},
 [0x007] = {{stat="HP", offset=65,multiplier=-1}},
 [0x008] = {{stat="HP", offset=97,multiplier=-1}},
 [0x009] = {{stat="MP", offset=1}},
 [0x00A] = {{stat="MP", offset=33}},
 [0x00B] = {{stat="MP", offset=65}},
 [0x00C] = {{stat="MP", offset=97}},
 [0x00D] = {{stat="MP", offset=1,multiplier=-1}},
 [0x00E] = {{stat="MP", offset=33,multiplier=-1}},
 [0x00F] = {{stat="MP", offset=65,multiplier=-1}},
 [0x010] = {{stat="MP", offset=97,multiplier=-1}},
 [0x011] = {{stat="HP", offset=1}, {stat="MP", offset=1}},
 [0x012] = {{stat="HP", offset=33}, {stat="MP", offset=33}},
 [0x013] = {{stat="HP", offset=1}, {stat="MP", offset=1,multiplier=-1}},
 [0x014] = {{stat="HP", offset=33}, {stat="MP", offset=33,multiplier=-1}},
 [0x015] = {{stat="HP", offset=1,multiplier=-1}, {stat="MP", offset=1}},
 [0x016] = {{stat="HP", offset=33,multiplier=-1}, {stat="MP", offset=33}},
 [0x017] = {{stat="Accuracy", offset=1}},
 [0x018] = {{stat="Accuracy", offset=1,multiplier=-1}},
 [0x019] = {{stat="Attack", offset=1}},
 [0x01A] = {{stat="Attack", offset=1,multiplier=-1}},
 [0x01B] = {{stat="Rng.Acc.", offset=1}},
 [0x01C] = {{stat="Rng.Acc.", offset=1,multiplier=-1}},
 [0x01D] = {{stat="Rng.Atk.", offset=1}},
 [0x01E] = {{stat="Rng.Atk.", offset=1,multiplier=-1}},
 [0x01F] = {{stat="Evasion", offset=1}},
 [0x020] = {{stat="Evasion", offset=1,multiplier=-1}},
 [0x021] = {{stat="DEF", offset=1}},
 [0x022] = {{stat="DEF", offset=1,multiplier=-1}},
 [0x023] = {{stat="Mag. Acc.", offset=1}},
 [0x024] = {{stat="Mag. Acc.", offset=1,multiplier=-1}},
 [0x025] = {{stat="Mag. Evasion", offset=1}},
 [0x026] = {{stat="Mag. Evasion", offset=1,multiplier=-1}},
 [0x027] = {{stat="Enmity", offset=1}},
 [0x028] = {{stat="Enmity", offset=1,multiplier=-1}},
 [0x029] = {{stat="Crit.hit rate", offset=1}},
 [0x02A] = {{stat="Enemy crit. hit rate ", offset=1,multiplier=-1}},
 [0x02B] = {{stat='"Charm"', offset=1}},
 [0x02C] = {{stat='"Store TP"', offset=1}, {stat='"Subtle Blow"', offset=1}},
 [0x02D] = {{stat="DMG:", offset=1}},
 [0x02E] = {{stat="DMG:", offset=1,multiplier=-1}},
 [0x02F] = {{stat="Delay:", offset=1,percent=true}},
 [0x030] = {{stat="Delay:", offset=1,multiplier=-1,percent=true}},
 [0x031] = {{stat="Haste", offset=1}},
 [0x032] = {{stat='"Slow"', offset=1}},
 [0x033] = {{stat="HP recovered while healing ", offset=1}},
 [0x034] = {{stat="MP recovered while healing ", offset=1}},
 [0x035] = {{stat="Spell interruption rate down ", offset=1,multiplier=-1,percent=true}},
 [0x036] = {{stat="Phys. dmg. taken ", offset=1,multiplier=-1,percent=true}},
 [0x037] = {{stat="Magic dmg. taken ", offset=1,multiplier=-1,percent=true}},
 [0x038] = {{stat="Breath dmg. taken ", offset=1,multiplier=-1,percent=true}},
 [0x039] = {{stat="Magic crit. hit rate ", offset=1}},
 [0x03A] = {{stat='"Mag.Def.Bns."', offset=1,multiplier=-1}},
 [0x03B] = {{stat='Latent effect: "Regain"', offset=1}},
 [0x03C] = {{stat='Latent effect: "Refresh"', offset=1}},
 [0x03D] = {{stat="Occ. inc. resist. to stat. ailments ", offset=1}},
 [0x03E] = {{stat="Accuracy", offset=33}},
 [0x03F] = {{stat="Rng.Acc.", offset=33}},
 [0x040] = {{stat="Mag. Acc.", offset=33}},
 [0x041] = {{stat="Attack", offset=33}},
 [0x042] = {{stat="Rng.Atk.", offset=33}},
 [0x043] = {{stat="All Songs", offset=1}},
 [0x044] = {{stat="Accuracy", offset=1},{stat="Attack", offset=1}},
 [0x045] = {{stat="Rng.Acc.", offset=1},{stat="Rng.Atk.", offset=1}},
 [0x046] = {{stat="Mag. Acc.", offset=1},{stat='"Mag.Atk.Bns."', offset=1}},
 [0x047] = {{stat="Damage taken", offset=1,multiplier=-1,percent=true}},
 
 [0x04A] = {{stat="Cap. Point", offset=1,percent=true}},
 [0x04B] = {{stat="Cap. Point", offset=33,percent=true}},
 [0x04C] = {{stat="DMG:", offset=33}},
 [0x04D] = {{stat="Delay:", offset=33,multiplier=-1,percent=true}},
 [0x04E] = {{stat="HP", offset=1,multiplier=2}},
 [0x04F] = {{stat="HP", offset=1,multiplier=3}},
 [0x050] = {{stat="Mag. Acc", offset=1}, {stat="/Mag. Dmg.", offset=1}},
 [0x051] = {{stat="Eva.", offset=1}, {stat="/Mag. Eva.", offset=1}},
 [0x052] = {{stat="MP", offset=1,multiplier=2}},
 [0x053] = {{stat="MP", offset=1,multiplier=3}},

 
 -- Need to figure out how to handle this section. The Pet: prefix is only used once despite how many augments are used.
 [0x060] = {{stat="Pet: Accuracy", offset=1}, {stat="Pet: Rng. Acc.", offset=1}}, -- Pet: Accuracy+5 Rng.Acc.+5
 [0x061] = {{stat="Pet: Attack", offset=1}, {stat="Pet: Rng.Atk.", offset=1}}, -- Pet: Attack +5 Rng.Atk.+5
 [0x062] = {{stat="Pet: Evasion", offset=1}},
 [0x063] = {{stat="Pet: DEF", offset=1}},
 [0x064] = {{stat="Pet: Mag. Acc.", offset=1}},
 [0x065] = {{stat='Pet: "Mag.Atk.Bns."', offset=1}},
 [0x066] = {{stat="Pet: Crit.hit rate ", offset=1}},
 [0x067] = {{stat="Pet: Enemy crit. hit rate ", offset=1,multiplier=-1}},
 [0x068] = {{stat="Pet: Enmity", offset=1}},
 [0x069] = {{stat="Pet: Enmity", offset=1,multiplier=-1}},
 [0x06A] = {{stat="Pet: Accuracy", offset=1}, {stat="Pet: Rng. Acc.", offset=1}},
 [0x06B] = {{stat="Pet: Attack", offset=1}, {stat="Pet: Rng.Atk.", offset=1}},
 [0x06C] = {{stat="Pet: Mag. Acc.", offset=1}, {stat='Pet: "Mag.Atk.Bns."', offset=1}},
 [0x06D] = {{stat='Pet: "Dbl.Atk."', offset=1}, {stat="Pet: Crit.hit rate ", offset=1}},
 [0x06E] = {{stat='Pet: "Regen"', offset=1}},
 [0x06F] = {{stat="Pet: Haste", offset=1}},
 [0x070] = {{stat="Pet: Damage taken ", offset=1,multiplier=-1,percent=true}},
 [0x071] = {{stat="Pet: Rng.Acc.", offset=1}},
 [0x072] = {{stat="Pet: Rng.Atk.", offset=1}},
 [0x073] = {{stat='Pet: "Store TP"', offset=1}},
 [0x074] = {{stat='Pet: "Subtle Blow"', offset=1}},
 [0x075] = {{stat="Pet: Mag. Evasion", offset=1}},
 [0x076] = {{stat="Pet: Phys. dmg. taken ", offset=1,multiplier=-1,percent=true}},
 [0x077] = {{stat='Pet: "Mag.Def.Bns."', offset=1}},
 [0x078] = {{stat='Avatar: "Mag.Atk.Bns."', offset=1}},
 [0x079] = {{stat='Pet: Breath', offset=1}},
 [0x07A] = {{stat='Pet: TP Bonus', offset=1, multiplier=20}},
 [0x07B] = {{stat='Pet: "Dbl. Atk."', offset=1}},
 [0x07C] = {{stat="Pet: Acc.", offset=1}, {stat="Pet: R.Acc.", offset=1}, {stat="Pet: Atk.", offset=1}, {stat="Pet: R.Atk.", offset=1}},
 [0x07D] = {{stat="Pet: M.Acc.", offset=1}, {stat="Pet: M.Dmg.", offset=1}},
 [0x07E] = {{stat='Pet: Magic Damage', offset=1}},
 [0x07F] = {{stat="Pet: Magic dmg. taken ", offset=1,multiplier=-1,percent=true}},

 [0x080] = {{stat="Pet:",offset = 0}},
 --[0x081: Accuracy +1 Ranged Acc. +0 | value + 1
 --[0x082: Attack +1 Ranged Atk. +0 | value + 1
 --[0x083: Mag. Acc. +1 "Mag.Atk.Bns."+0 | value + 1
 --[0x084: "Double Atk."+1 "Crit. hit +0 | value + 1

 --0x080~0x084 are pet augs with a pair of stats with 0x080 being just "Pet:"
 --the second stat starts at 0. the previous pet augs add +2. the first previous non pet aug adds +2. any other non pet aug will add +1.
 --any aug >= 0x032 will be added after the pet stack and will not be counted to increase the 2nd pet's aug stat and will be prolly assigned to the pet.
 --https://gist.github.com/giulianoriccio/6df4fbd1f2a166fed041/raw/4e1d1103e7fe0e69d25f8264387506b5e38296a7/augs
 
 -- Byrth's note: These augments are just weird and I have no evidence that SE actually uses them.
 -- The first argument of the augment has its potency calculated normally (using the offset). The second argument
 -- has its potency calculated using an offset equal to 2*its position in the augment list (re-ordered from biggest to lowest IDs)
 -- So having 0x80 -> 0x81 -> 0x82 results in the same augments as 0x80 -> 0x82 -> 0x81
 -- In that case, Acc/Atk would be determined by the normal offset, but Racc would be +2 and RAtk would be +4

 [0x085] = {{stat='"Mag.Atk.Bns."', offset=1}},
 [0x086] = {{stat='"Mag.Def.Bns."', offset=1}},
 [0x087] = {{stat="Avatar:",offset=0}},
 
 [0x089] = {{stat='"Regen"', offset=1}},
 [0x08A] = {{stat='"Refresh"', offset=1}},
 [0x08B] = {{stat='"Rapid Shot"', offset=1}},
 [0x08C] = {{stat='"Fast Cast"', offset=1}},
 [0x08D] = {{stat='"Conserve MP"', offset=1}},
 [0x08E] = {{stat='"Store TP"', offset=1}},
 [0x08F] = {{stat='"Dbl.Atk."', offset=1}},
 [0x090] = {{stat='"Triple Atk."', offset=1}},
 [0x091] = {{stat='"Counter"', offset=1}},
 [0x092] = {{stat='"Dual Wield"', offset=1}},
 [0x093] = {{stat='"Treasure Hunter"', offset=1}},
 [0x094] = {{stat='"Gilfinder"', offset=1}},
 
 [0x097] = {{stat='"Martial Arts"', offset=1}},
 
 [0x099] = {{stat='"Shield Mastery"', offset=1}},
 
 [0x0B0] = {{stat='"Resist Sleep"', offset=1}},
 [0x0B1] = {{stat='"Resist Poison"', offset=1}},
 [0x0B2] = {{stat='"Resist Paralyze"', offset=1}},
 [0x0B3] = {{stat='"Resist Blind"', offset=1}},
 [0x0B4] = {{stat='"Resist Silence"', offset=1}},
 [0x0B5] = {{stat='"Resist Petrify"', offset=1}},
 [0x0B6] = {{stat='"Resist Virus"', offset=1}},
 [0x0B7] = {{stat='"Resist Curse"', offset=1}},
 [0x0B8] = {{stat='"Resist Stun"', offset=1}},
 [0x0B9] = {{stat='"Resist Bind"', offset=1}},
 [0x0BA] = {{stat='"Resist Gravity"', offset=1}},
 [0x0BB] = {{stat='"Resist Slow"', offset=1}},
 [0x0BC] = {{stat='"Resist Charm"', offset=1}},
 
 [0x0C2] = {{stat='"Kick Attacks"', offset=1}},
 [0x0C3] = {{stat='"Subtle Blow"', offset=1}},

 [0x0C6] = {{stat='"Zanshin"', offset=1}},

 [0x0D3] = {{stat='"Snapshot"', offset=1}},
 [0x0D4] = {{stat='"Recycle"', offset=1}},

 [0x0D7] = {{stat='"Ninja tool expertise"', offset=1}},
 
 [0x0E9] = {{stat='"Blood Boon"', offset=1}},
 
 [0x0ED] = {{stat='"Occult Acumen"', offset=1}},

 [0x101] = {{stat="Hand-to-Hand skill ", offset=1}},
 [0x102] = {{stat="Dagger skill ", offset=1}},
 [0x103] = {{stat="Sword skill ", offset=1}},
 [0x104] = {{stat="Great Sword skill ", offset=1}},
 [0x105] = {{stat="Axe skill ", offset=1}},
 [0x106] = {{stat="Great Axe skill ", offset=1}},
 [0x107] = {{stat="Scythe skill ", offset=1}},
 [0x108] = {{stat="Polearm skill ", offset=1}},
 [0x109] = {{stat="Katana skill ", offset=1}},
 [0x10A] = {{stat="Great Katana skill ", offset=1}},
 [0x10B] = {{stat="Club skill ", offset=1}},
 [0x10C] = {{stat="Staff skill ", offset=1}},

 [0x116] = {{stat="Melee skill ", offset=1}}, -- Automaton
 [0x117] = {{stat="Ranged skill ", offset=1}}, -- Automaton
 [0x118] = {{stat="Magic skill ", offset=1}}, -- Automaton
 [0x119] = {{stat="Archery skill ", offset=1}},
 [0x11A] = {{stat="Marksmanship skill ", offset=1}},
 [0x11B] = {{stat="Throwing skill ", offset=1}},

 [0x11E] = {{stat="Shield skill ", offset=1}},

 [0x120] = {{stat="Divine magic skill ", offset=1}},
 [0x121] = {{stat="Healing magic skill ", offset=1}},
 [0x122] = {{stat="Enha.mag. skill ", offset=1}},
 [0x123] = {{stat="Enfb.mag. skill ", offset=1}},
 [0x124] = {{stat="Elem. magic skill ", offset=1}},
 [0x125] = {{stat="Dark magic skill ", offset=1}},
 [0x126] = {{stat="Summoning magic skill ", offset=1}},
 [0x127] = {{stat="Ninjutsu skill ", offset=1}},
 [0x128] = {{stat="Singing skill ", offset=1}},
 [0x129] = {{stat="String instrument skill ", offset=1}},
 [0x12A] = {{stat="Wind instrument skill ", offset=1}},
 [0x12B] = {{stat="Blue Magic skill ", offset=1}},
 [0x12C] = {{stat="Geomancy Skill ", offset=1}},
 [0x12D] = {{stat="Handbell Skill ", offset=1}},

 [0x140] = {{stat='"Blood Pact" ability delay ', offset=1,multiplier=-1}},
 [0x141] = {{stat='"Avatar perpetuation cost" ', offset=1,multiplier=-1}},
 [0x142] = {{stat="Song spellcasting time ", offset=1,multiplier=-1,percent=true}},
 [0x143] = {{stat='"Cure" spellcasting time ', offset=1,multiplier=-1,percent=true}},
 [0x144] = {{stat='"Call Beast" ability delay ', offset=1,multiplier=-1}},
 [0x145] = {{stat='"Quick Draw" ability delay ', offset=1,multiplier=-1}},
 [0x146] = {{stat="Weapon Skill Acc.", offset=1}},
 [0x147] = {{stat="Weapon skill damage ", offset=1,percent=true}},
 [0x148] = {{stat="Crit. hit damage ", offset=1,percent=true}},
 [0x149] = {{stat='"Cure" potency ', offset=1,percent=true}},
 [0x14A] = {{stat='"Waltz" potency ', offset=1,percent=true}},
 [0x14B] = {{stat='"Waltz" ability delay ', offset=1,multiplier=-1}},
 [0x14C] = {{stat="Sklchn.dmg.", offset=1,percent=true}},
 [0x14D] = {{stat='"Conserve TP"', offset=1}},
 [0x14E] = {{stat="Magic burst dmg.", offset=1,percent=true}},
 [0x14F] = {{stat="Mag. crit. hit dmg. ", offset=1,percent=true}},
 [0x150] = {{stat='"Sic" and "Ready" ability delay ', offset=1,multiplier=-1}},
 [0x151] = {{stat="Song recast delay ", offset=1,multiplier=-1}},
 [0x152] = {{stat='"Barrage"', offset=1}},
 [0x153] = {{stat='"Elemental Siphon"', offset=1, multiplier=5}},
 [0x154] = {{stat='"Phantom Roll" ability delay ', offset=1,multiplier=-1}},
 [0x155] = {{stat='"Repair" potency ', offset=1,percent=true}},
 [0x156] = {{stat='"Waltz" TP cost ', offset=1,multiplier=-1}},
 [0x157] = {{stat='"Drain" and "Aspir" potency ', offset=1}},

 [0x15E] = {{stat="Occ. maximizes magic accuracy ", offset=1,percent=true}},
 [0x15F] = {{stat="Occ. quickens spellcasting ", offset=1,percent=true}},
 [0x160] = {{stat="Occ. grants dmg. bonus based on TP ", offset=1,percent=true}},
 [0x161] = {{stat="TP Bonus ", offset=1, multiplier=50}},
 [0x162] = {{stat="Quadruple Attack ", offset=1}},

 [0x164] = {{stat='Potency of "Cure" effect received', offset=1, percent=true}},
 
 [0x168] = {{stat="Save TP ", offset=1, multiplier=10}},
 
 [0x16A] = {{stat="Magic Damage ", offset=1}},
 [0x16B] = {{stat="Chance of successful block ", offset=1}},
 [0x16E] = {{stat="Blood Pact ab. del. II ", offset=1, multiplier=-1}},
 [0x170] = {{stat="Phalanx ", offset=1}},
 [0x171] = {{stat="Blood Pact Dmg.", offset=1}},
 [0x172] = {{stat='"Rev. Flourish"', offset=1}},
 [0x173] = {{stat='"Regen" potency', offset=1}},
 [0x174] = {{stat='"Embolden"', offset=1}},
 -- Empties are Numbered up to 0x17F. Their stat is their index + 1
 [0x200] = {{stat="STR", offset=1}},
 [0x201] = {{stat="DEX", offset=1}},
 [0x202] = {{stat="VIT", offset=1}},
 [0x203] = {{stat="AGI", offset=1}},
 [0x204] = {{stat="INT", offset=1}},
 [0x205] = {{stat="MND", offset=1}},
 [0x206] = {{stat="CHR", offset=1}},
 [0x207] = {{stat="STR", offset=1,multiplier=-1}},
 [0x208] = {{stat="DEX", offset=1,multiplier=-1}},
 [0x209] = {{stat="VIT", offset=1,multiplier=-1}},
 [0x20A] = {{stat="AGI", offset=1,multiplier=-1}},
 [0x20B] = {{stat="INT", offset=1,multiplier=-1}},
 [0x20C] = {{stat="MND", offset=1,multiplier=-1}},
 [0x20D] = {{stat="CHR", offset=1,multiplier=-1}},
 -- The below values aren't really right
 -- They need to be "Ceiling'd"
 [0x20E] = {{stat="STR", offset=1}, {stat="DEX", offset=1, multiplier=-0.5}, {stat="VIT", offset=1, multiplier=-0.5}},
 [0x20F] = {{stat="STR", offset=1}, {stat="DEX", offset=1, multiplier=-0.5}, {stat="AGI", offset=1, multiplier=-0.5}},
 [0x210] = {{stat="STR", offset=1}, {stat="VIT", offset=1, multiplier=-0.5}, {stat="AGI", offset=1, multiplier=-0.5}},
 [0x211] = {{stat="STR", offset=1, multiplier=-0.5}, {stat="DEX", offset=1}, {stat="VIT", offset=1, multiplier=-0.5}},
 [0x212] = {{stat="STR", offset=1, multiplier=-0.5}, {stat="DEX", offset=1}, {stat="AGI", offset=1, multiplier=-0.5}},
 [0x213] = {{stat="DEX", offset=1}, {stat="VIT", offset=1, multiplier=-0.5}, {stat="AGI", offset=1, multiplier=-0.5}},
 [0x214] = {{stat="STR", offset=1, multiplier=-0.5}, {stat="DEX", offset=1, multiplier=-0.5}, {stat="VIT", offset=1}},
 [0x215] = {{stat="STR", offset=1, multiplier=-0.5}, {stat="VIT", offset=1}, {stat="AGI", offset=1, multiplier=-0.5}},
 [0x216] = {{stat="DEX", offset=1, multiplier=-0.5}, {stat="VIT", offset=1}, {stat="AGI", offset=1, multiplier=-0.5}},
 [0x217] = {{stat="STR", offset=1, multiplier=-0.5}, {stat="DEX", offset=1, multiplier=-0.5}, {stat="AGI", offset=1}},
 [0x218] = {{stat="STR", offset=1, multiplier=-0.5}, {stat="VIT", offset=1, multiplier=-0.5}, {stat="AGI", offset=1}},
 [0x219] = {{stat="DEX", offset=1, multiplier=-0.5}, {stat="VIT", offset=1, multiplier=-0.5}, {stat="AGI", offset=1}},
 [0x21A] = {{stat="AGI", offset=1}, {stat="INT", offset=1, multiplier=-0.5}, {stat="MND", offset=1, multiplier=-0.5}},
 [0x21B] = {{stat="AGI", offset=1}, {stat="INT", offset=1, multiplier=-0.5}, {stat="CHR", offset=1, multiplier=-0.5}},
 [0x21C] = {{stat="AGI", offset=1}, {stat="MND", offset=1, multiplier=-0.5}, {stat="CHR", offset=1, multiplier=-0.5}},
 [0x21D] = {{stat="AGI", offset=1, multiplier=-0.5}, {stat="INT", offset=1}, {stat="MND", offset=1, multiplier=-0.5}},
 [0x21E] = {{stat="AGI", offset=1, multiplier=-0.5}, {stat="INT", offset=1}, {stat="CHR", offset=1, multiplier=-0.5}},
 [0x21F] = {{stat="INT", offset=1}, {stat="MND", offset=1, multiplier=-0.5}, {stat="CHR", offset=1, multiplier=-0.5}},
 [0x220] = {{stat="AGI", offset=1, multiplier=-0.5}, {stat="INT", offset=1, multiplier=-0.5}, {stat="MND", offset=1}},
 [0x221] = {{stat="AGI", offset=1, multiplier=-0.5}, {stat="MND", offset=1}, {stat="CHR", offset=1, multiplier=-0.5}},
 [0x222] = {{stat="INT", offset=1, multiplier=-0.5}, {stat="MND", offset=1}, {stat="CHR", offset=1, multiplier=-0.5}},
 [0x223] = {{stat="AGI", offset=1, multiplier=-0.5}, {stat="INT", offset=1, multiplier=-0.5}, {stat="CHR", offset=1}},
 [0x224] = {{stat="AGI", offset=1, multiplier=-0.5}, {stat="MND", offset=1, multiplier=-0.5}, {stat="CHR", offset=1}},
 [0x225] = {{stat="INT", offset=1, multiplier=-0.5}, {stat="MND", offset=1, multiplier=-0.5}, {stat="CHR", offset=1}},
 [0x226] = {{stat="STR", offset=1}, {stat="DEX", offset=1}},
 [0x227] = {{stat="STR", offset=1}, {stat="VIT", offset=1}},
 [0x228] = {{stat="STR", offset=1}, {stat="AGI", offset=1}},
 [0x229] = {{stat="DEX", offset=1}, {stat="AGI", offset=1}},
 [0x22A] = {{stat="INT", offset=1}, {stat="MND", offset=1}},
 [0x22B] = {{stat="MND", offset=1}, {stat="CHR", offset=1}},
 [0x22C] = {{stat="INT", offset=1}, {stat="MND", offset=1}, {stat="CHR", offset=1}},
 [0x22D] = {{stat="STR", offset=1}, {stat="CHR", offset=1}},
 [0x22E] = {{stat="STR", offset=1}, {stat="INT", offset=1}},
 [0x22F] = {{stat="STR", offset=1}, {stat="MND", offset=1}},

 [0x2E4] = {{stat="DMG:", offset=1}},
 [0x2E5] = {{stat="DMG:", offset=33}},
 [0x2E6] = {{stat="DMG:", offset=65}},
 [0x2E7] = {{stat="DMG:", offset=97}},
 [0x2E8] = {{stat="DMG:", offset=1,multiplier=-1}},
 [0x2E9] = {{stat="DMG:", offset=33,multiplier=-1}},
 [0x2EA] = {{stat="DMG:", offset=1}},
 [0x2EB] = {{stat="DMG:", offset=33}},
 [0x2EC] = {{stat="DMG:", offset=65}},
 [0x2ED] = {{stat="DMG:", offset=97}},
 [0x2EE] = {{stat="DMG:", offset=1,multiplier=-1}},
 [0x2EF] = {{stat="DMG:", offset=33,multiplier=-1}},
 [0x2F0] = {{stat="Delay:", offset=1}},
 [0x2F1] = {{stat="Delay:", offset=33}},
 [0x2F2] = {{stat="Delay:", offset=65}},
 [0x2F3] = {{stat="Delay:", offset=97}},
 [0x2F4] = {{stat="Delay:", offset=1,multiplier=-1}},
 [0x2F5] = {{stat="Delay:", offset=33,multiplier=-1}},
 [0x2F6] = {{stat="Delay:", offset=65,multiplier=-1}},
 [0x2F7] = {{stat="Delay:", offset=97,multiplier=-1}},
 [0x2F8] = {{stat="Delay:", offset=1}},
 [0x2F9] = {{stat="Delay:", offset=33}},
 [0x2FA] = {{stat="Delay:", offset=65}},
 [0x2FB] = {{stat="Delay:", offset=97}},
 [0x2FC] = {{stat="Delay:", offset=1,multiplier=-1}},
 [0x2FD] = {{stat="Delay:", offset=33,multiplier=-1}},
 [0x2FE] = {{stat="Delay:", offset=65,multiplier=-1}},
 [0x2FF] = {{stat="Delay:", offset=97,multiplier=-1}},
 [0x300] = {{stat="Fire resistance", offset=1}},
 [0x301] = {{stat="Ice resistance", offset=1}},
 [0x302] = {{stat="Wind resistance", offset=1}},
 [0x303] = {{stat="Earth resistance", offset=1}},
 [0x304] = {{stat="Lightning resistance", offset=1}},
 [0x305] = {{stat="Water resistance", offset=1}},
 [0x306] = {{stat="Light resistance", offset=1}},
 [0x307] = {{stat="Dark resistance", offset=1}},
 [0x308] = {{stat="Fire resistance", offset=1,multiplier=-1}},
 [0x309] = {{stat="Ice resistance", offset=1,multiplier=-1}},
 [0x30A] = {{stat="Wind resistance", offset=1,multiplier=-1}},
 [0x30B] = {{stat="Earth resistance", offset=1,multiplier=-1}},
 [0x30C] = {{stat="Lightning resistance", offset=1,multiplier=-1}},
 [0x30D] = {{stat="Water resistance", offset=1,multiplier=-1}},
 [0x30E] = {{stat="Light resistance", offset=1,multiplier=-1}},
 [0x30F] = {{stat="Dark resistance", offset=1,multiplier=-1}},
 [0x310] = {{stat="Fire resistance", offset=1}, {stat="Water resistance", offset=1,multiplier=-1}},
 [0x311] = {{stat="Fire resistance", offset=1,multiplier=-1}, {stat="Ice resistance", offset=1}},
 [0x312] = {{stat="Ice resistance", offset=1,multiplier=-1}, {stat="Wind resistance", offset=1}},
 [0x313] = {{stat="Wind resistance", offset=1,multiplier=-1}, {stat="Earth resistance", offset=1}},
 [0x314] = {{stat="Earth resistance", offset=1,multiplier=-1}, {stat="Lightning resistance", offset=1}},
 [0x315] = {{stat="Lightning resistance", offset=1,multiplier=-1}, {stat="Water resistance", offset=1}},
 [0x316] = {{stat="Light resistance", offset=1}, {stat="Dark resistance", offset=1,multiplier=-1}},
 [0x317] = {{stat="Light resistance", offset=1,multiplier=-1}, {stat="Dark resistance", offset=1}},
 [0x318] = {{stat="Fire resistance", offset=1}, {stat="Wind resistance", offset=1}, {stat="Lightning resistance", offset=1}, {stat="Light resistance", offset=1}},
 [0x319] = {{stat="Ice resistance", offset=1}, {stat="Earth resistance", offset=1}, {stat="Water resistance", offset=1}, {stat="Dark resistance", offset=1}},
 [0x31A] = {{stat="Fire resistance", offset=1}, {stat="Ice resistance", offset=1,multiplier=-1}, {stat="Wind resistance", offset=1}, {stat="Earth resistance", offset=1,multiplier=-1}, {stat="Lightning resistance", offset=1}, {stat="Water resistance", offset=1,multiplier=-1}, {stat="Light resistance", offset=1}, {stat="Dark resistance", offset=1,multiplier=-1}},
 [0x31B] = {{stat="Fire resistance", offset=1,multiplier=-1}, {stat="Ice resistance", offset=1}, {stat="Wind resistance", offset=1,multiplier=-1}, {stat="Earth resistance", offset=1}, {stat="Lightning resistance", offset=1,multiplier=-1}, {stat="Water resistance", offset=1}, {stat="Light resistance", offset=1,multiplier=-1}, {stat="Dark resistance", offset=1}},
 [0x31C] = {{stat="Fire resistance", offset=1}, {stat="Ice resistance", offset=1}, {stat="Wind resistance", offset=1}, {stat="Earth resistance", offset=1}, {stat="Lightning resistance", offset=1}, {stat="Water resistance", offset=1}, {stat="Light resistance", offset=1}, {stat="Dark resistance", offset=1}},
 [0x31D] = {{stat="Fire resistance", offset=1,multiplier=-1}, {stat="Ice resistance", offset=1,multiplier=-1}, {stat="Wind resistance", offset=1,multiplier=-1}, {stat="Earth resistance", offset=1,multiplier=-1}, {stat="Lightning resistance", offset=1,multiplier=-1}, {stat="Water resistance", offset=1,multiplier=-1}, {stat="Light resistance", offset=1,multiplier=-1}, {stat="Dark resistance", offset=1,multiplier=-1}},

 [0x340] = {{stat="Add.eff.:Fire Dmg.", offset=5}},
 [0x341] = {{stat="Add.eff.:Ice Dmg.", offset=5}},
 [0x342] = {{stat="Add.eff.:Wind Dmg.", offset=5}},
 [0x343] = {{stat="Add.eff.:Earth Dmg.", offset=5}},
 [0x344] = {{stat="Add.eff.:Lightning Dmg.", offset=5}},
 [0x345] = {{stat="Add.eff.:Water Dmg.", offset=5}},
 [0x346] = {{stat="Add.eff.:Light Dmg.", offset=5}},
 [0x347] = {{stat="Add.eff.:Dark Dmg.", offset=5}},
 [0x348] = {{stat="Add.eff.:Disease", offset=1}},
 [0x349] = {{stat="Add.eff.:Paralysis", offset=1}},
 [0x34A] = {{stat="Add.eff.:Silence", offset=1}},
 [0x34B] = {{stat="Add.eff.:Slow", offset=1}},
 [0x34C] = {{stat="Add.eff.:Stun", offset=1}},
 [0x34D] = {{stat="Add.eff.:Poison", offset=1}},
 [0x34E] = {{stat="Add.eff.:Flash", offset=1}},
 [0x34F] = {{stat="Add.eff.:Blindness", offset=1}},
 [0x350] = {{stat="Add.eff.:Weakens def.", offset=1}},
 [0x351] = {{stat="Add.eff.:Sleep", offset=1}},
 [0x352] = {{stat="Add.eff.:Weakens atk.", offset=1}},
 [0x353] = {{stat="Add.eff.:Impairs evasion", offset=1}},
 [0x354] = {{stat="Add.eff.:Lowers acc.", offset=1}},
 [0x355] = {{stat="Add.eff.:Lowers mag.eva.", offset=1}},
 [0x356] = {{stat="Add.eff.:Lowers mag.atk.", offset=1}},
 [0x357] = {{stat="Add.eff.:Lowers mag.def.", offset=1}},
 [0x358] = {{stat="Add.eff.:Lowers mag.acc.", offset=1}},
 -- 0x359 = 475
 [0x380] = {{stat="Sword enhancement spell damage ", offset=1}},
 [0x381] = {{stat='Enhances "Souleater" effect ', offset=1,percent=true}},
 
 -- This is actually a range for static augments that uses all the bits.
 
 [0x390] = {Secondary_Handling = true},
 [0x391] = {Secondary_Handling = true},
 [0x392] = {Secondary_Handling = true},
 -- The below enhancements aren't visible if their value is 0.
 [0x3A0] = {{stat="Fire Affinity ", offset=0}},
 [0x3A1] = {{stat="Ice Affinity ", offset=0}},
 [0x3A2] = {{stat="Wind Affinity ", offset=0}},
 [0x3A3] = {{stat="Earth Affinity ", offset=0}},
 [0x3A4] = {{stat="Lightning Affinity ", offset=0}},
 [0x3A5] = {{stat="Water Affinity ", offset=0}},
 [0x3A6] = {{stat="Light Affinity ", offset=0}},
 [0x3A7] = {{stat="Dark Affinity ", offset=0}},
 [0x3A8] = {{stat="Fire Affinity: Magic Accuracy", offset=0}},
 [0x3A9] = {{stat="Ice Affinity: Magic Accuracy", offset=0}},
 [0x3AA] = {{stat="Wind Affinity: Magic Accuracy", offset=0}},
 [0x3AB] = {{stat="Earth Affinity: Magic Accuracy", offset=0}},
 [0x3AC] = {{stat="Lightning Affinity: Magic Accuracy", offset=0}},
 [0x3AD] = {{stat="Water Affinity: Magic Accuracy", offset=0}},
 [0x3AE] = {{stat="Light Affinity: Magic Accuracy", offset=0}},
 [0x3AF] = {{stat="Dark Affinity: Magic Accuracy", offset=0}},
 [0x3B0] = {{stat="Fire Affinity: Magic Damage", offset=0}},
 [0x3B1] = {{stat="Ice Affinity: Magic Damage", offset=0}},
 [0x3B2] = {{stat="Wind Affinity: Magic Damage", offset=0}},
 [0x3B3] = {{stat="Earth Affinity: Magic Damage", offset=0}},
 [0x3B4] = {{stat="Lightning Affinity: Magic Damage", offset=0}},
 [0x3B5] = {{stat="Water Affinity: Magic Damage", offset=0}},
 [0x3B6] = {{stat="Light Affinity: Magic Damage", offset=0}},
 [0x3B7] = {{stat="Dark Affinity: Magic Damage", offset=0}},
 [0x3B8] = {{stat="Fire Affinity: Avatar perp. cost", offset=0}},
 [0x3B9] = {{stat="Ice Affinity: Avatar perp. cost", offset=0}},
 [0x3BA] = {{stat="Wind Affinity: Avatar perp. cost", offset=0}},
 [0x3BB] = {{stat="Earth Affinity: Avatar perp. cost", offset=0}},
 [0x3BC] = {{stat="Lightning Affinity: Avatar perp. cost", offset=0}},
 [0x3BD] = {{stat="Water Affinity: Avatar perp. cost", offset=0}},
 [0x3BE] = {{stat="Light Affinity: Avatar perp. cost", offset=0}},
 [0x3BF] = {{stat="Dark Affinity: Avatar perp. cost", offset=0}},
 [0x3C0] = {{stat="Fire Affinity: Magic Accuracy", offset=0},{stat="Fire Affinity: Recast time", offset=1, multiplier=-2, percent=true}},
 [0x3C1] = {{stat="Ice Affinity: Magic Accuracy", offset=0},{stat="Ice Affinity: Recast time", offset=1, multiplier=-2, percent=true}},
 [0x3C2] = {{stat="Wind Affinity: Magic Accuracy", offset=0},{stat="Wind Affinity: Recast time", offset=1, multiplier=-2, percent=true}},
 [0x3C3] = {{stat="Earth Affinity: Magic Accuracy", offset=0},{stat="Earth Affinity: Recast time", offset=1, multiplier=-2, percent=true}},
 [0x3C4] = {{stat="Lightning Affinity: Magic Accuracy", offset=0},{stat="Lightning Affinity: Recast time", offset=1, multiplier=-2, percent=true}},
 [0x3C5] = {{stat="Water Affinity: Magic Accuracy", offset=0},{stat="Water Affinity: Recast time", offset=1, multiplier=-2, percent=true}},
 [0x3C6] = {{stat="Light Affinity: Magic Accuracy", offset=0},{stat="Light Affinity: Recast time", offset=1, multiplier=-2, percent=true}},
 [0x3C7] = {{stat="Dark Affinity: Magic Accuracy", offset=0},{stat="Dark Affinity: Recast time", offset=1, multiplier=-2, percent=true}},
 [0x3C8] = {{stat="Fire Affinity: Magic Damage", offset=0},{stat="Fire Affinity: Casting time", offset=1, multiplier=-2, percent=true}},
 [0x3C9] = {{stat="Ice Affinity: Magic Damage", offset=0},{stat="Ice Affinity: Casting time", offset=1, multiplier=-2, percent=true}},
 [0x3CA] = {{stat="Wind Affinity: Magic Damage", offset=0},{stat="Wind Affinity: Casting time", offset=1, multiplier=-2, percent=true}},
 [0x3CB] = {{stat="Earth Affinity: Magic Damage", offset=0},{stat="Earth Affinity: Casting time", offset=1, multiplier=-2, percent=true}},
 [0x3CC] = {{stat="Lightning Affinity: Magic Damage", offset=0},{stat="Lightning Affinity: Casting time", offset=1, multiplier=-2, percent=true}},
 [0x3CD] = {{stat="Water Affinity: Magic Damage", offset=0},{stat="Water Affinity: Casting time", offset=1, multiplier=-2, percent=true}},
 [0x3CE] = {{stat="Light Affinity: Magic Damage", offset=0},{stat="Light Affinity: Casting time", offset=1, multiplier=-2, percent=true}},
 [0x3CF] = {{stat="Dark Affinity: Magic Damage", offset=0},{stat="Dark Affinity: Casting time", offset=1, multiplier=-2, percent=true}},
 [0x3D0] = {{stat='Fire Affin.: "Blood Pact" delay ', offset=1}},
 [0x3D1] = {{stat='Ice Affin.: "Blood Pact" delay ', offset=1}},
 [0x3D2] = {{stat='Wind Affin.: "Blood Pact" delay ', offset=1}},
 [0x3D3] = {{stat='Earth Affin.: "Blood Pact" delay ', offset=1}},
 [0x3D4] = {{stat='Lightning Affin.: "Blood Pact" delay ', offset=1}},
 [0x3D5] = {{stat='Water Affin.: "Blood Pact" delay ', offset=1}},
 [0x3D6] = {{stat='Light Affin.: "Blood Pact" delay ', offset=1}},
 [0x3D7] = {{stat='Dark Affin.: "Blood Pact" delay ', offset=1}},
 [0x3D8] = {{stat="Fire Affinity: Recast time", offset=1, multiplier=-2, percent=true}},
 [0x3D9] = {{stat="Ice Affinity: Recast time", offset=1, multiplier=-2, percent=true}},
 [0x3DA] = {{stat="Wind Affinity: Recast time", offset=1, multiplier=-2, percent=true}},
 [0x3DB] = {{stat="Earth Affinity: Recast time", offset=1, multiplier=-2, percent=true}},
 [0x3DC] = {{stat="Lightning Affinity: Recast time", offset=1, multiplier=-2, percent=true}},
 [0x3DD] = {{stat="Water Affinity: Recast time", offset=1, multiplier=-2, percent=true}},
 [0x3DE] = {{stat="Light Affinity: Recast time", offset=1, multiplier=-2, percent=true}},
 [0x3DF] = {{stat="Dark Affinity: Recast time", offset=1, multiplier=-2, percent=true}},
 [0x3E0] = {{stat="Fire Affinity: Casting time", offset=1, multiplier=-2, percent=true}},
 [0x3E1] = {{stat="Ice Affinity: Casting time", offset=1, multiplier=-2, percent=true}},
 [0x3E2] = {{stat="Wind Affinity: Casting time", offset=1, multiplier=-2, percent=true}},
 [0x3E3] = {{stat="Earth Affinity: Casting time", offset=1, multiplier=-2, percent=true}},
 [0x3E4] = {{stat="Lightning Affinity: Casting time", offset=1, multiplier=-2, percent=true}},
 [0x3E5] = {{stat="Water Affinity: Casting time", offset=1, multiplier=-2, percent=true}},
 [0x3E6] = {{stat="Light Affinity: Casting time", offset=1, multiplier=-2, percent=true}},
 [0x3E7] = {{stat="Dark Affinity: Casting time", offset=1, multiplier=-2, percent=true}},
 [0x3E8] = {{stat="Fire Affinity: Magic Accuracy", offset=0},{stat="Fire Affinity: Casting time", offset=1, multiplier=-6, percent=true}},
 [0x3E9] = {{stat="Ice Affinity: Magic Accuracy", offset=0},{stat="Ice Affinity: Casting time", offset=1, multiplier=-6, percent=true}},
 [0x3EA] = {{stat="Wind Affinity: Magic Accuracy", offset=0},{stat="Wind Affinity: Casting time", offset=1, multiplier=-6, percent=true}},
 [0x3EB] = {{stat="Earth Affinity: Magic Accuracy", offset=0},{stat="Earth Affinity: Casting time", offset=1, multiplier=-6, percent=true}},
 [0x3EC] = {{stat="Lightning Affinity: Magic Accuracy", offset=0},{stat="Lightning Affinity: Casting time", offset=1, multiplier=-6, percent=true}},
 [0x3ED] = {{stat="Water Affinity: Magic Accuracy", offset=0},{stat="Water Affinity: Casting time", offset=1, multiplier=-6, percent=true}},
 [0x3EE] = {{stat="Light Affinity: Magic Accuracy", offset=0},{stat="Light Affinity: Casting time", offset=1, multiplier=-6, percent=true}},
 [0x3EF] = {{stat="Dark Affinity: Magic Accuracy", offset=0},{stat="Dark Affinity: Casting time", offset=1, multiplier=-6, percent=true}},
 [0x3F0] = {{stat="Fire Affinity: Magic Damage", offset=0},{stat="Fire Affinity: Recast time", offset=1, multiplier=-6, percent=true}},
 [0x3F1] = {{stat="Ice Affinity: Magic Damage", offset=0},{stat="Ice Affinity: Recast time", offset=1, multiplier=-6, percent=true}},
 [0x3F2] = {{stat="Wind Affinity: Magic Damage", offset=0},{stat="Wind Affinity: Recast time", offset=1, multiplier=-6, percent=true}},
 [0x3F3] = {{stat="Earth Affinity: Magic Damage", offset=0},{stat="Earth Affinity: Recast time", offset=1, multiplier=-6, percent=true}},
 [0x3F4] = {{stat="Lightning Affinity: Magic Damage", offset=0},{stat="Lightning Affinity: Recast time", offset=1, multiplier=-6, percent=true}},
 [0x3F5] = {{stat="Water Affinity: Magic Damage", offset=0},{stat="Water Affinity: Recast time", offset=1, multiplier=-6, percent=true}},
 [0x3F6] = {{stat="Light Affinity: Magic Damage", offset=0},{stat="Light Affinity: Recast time", offset=1, multiplier=-6, percent=true}},
 [0x3F7] = {{stat="Dark Affinity: Magic Damage", offset=0},{stat="Dark Affinity: Recast time", offset=1, multiplier=-6, percent=true}},
 
 [0x400] = {{stat="Backhand Blow:DMG:", offset=1,multiplier=5,percent=true}},
 [0x401] = {{stat="Spinning Attack:DMG:", offset=1,multiplier=5,percent=true}},
 [0x402] = {{stat="Howling Fist:DMG:", offset=1,multiplier=5,percent=true}},
 [0x403] = {{stat="Dragon Kick:DMG:", offset=1,multiplier=5,percent=true}},
 [0x404] = {{stat="Viper Bite:DMG:", offset=1,multiplier=5,percent=true}},
 [0x405] = {{stat="Shadowstitch:DMG:", offset=1,multiplier=5,percent=true}},
 [0x406] = {{stat="Cyclone:DMG:", offset=1,multiplier=5,percent=true}},
 [0x407] = {{stat="Evisceration:DMG:", offset=1,multiplier=5,percent=true}},
 [0x408] = {{stat="Burning Blade:DMG:", offset=1,multiplier=5,percent=true}},
 [0x409] = {{stat="Shining Blade:DMG:", offset=1,multiplier=5,percent=true}},
 [0x40A] = {{stat="Circle Blade:DMG:", offset=1,multiplier=5,percent=true}},
 [0x40B] = {{stat="Savage Blade:DMG:", offset=1,multiplier=5,percent=true}},
 [0x40C] = {{stat="Freezebite:DMG:", offset=1,multiplier=5,percent=true}},
 [0x40D] = {{stat="Shockwave:DMG:", offset=1,multiplier=5,percent=true}},
 [0x40E] = {{stat="Ground Strike:DMG:", offset=1,multiplier=5,percent=true}},
 [0x40F] = {{stat="Sickle Moon:DMG:", offset=1,multiplier=5,percent=true}},
 [0x410] = {{stat="Gale Axe:DMG:", offset=1,multiplier=5,percent=true}},
 [0x411] = {{stat="Spinning Axe:DMG:", offset=1,multiplier=5,percent=true}},
 [0x412] = {{stat="Calamity:DMG:", offset=1,multiplier=5,percent=true}},
 [0x413] = {{stat="Decimation:DMG:", offset=1,multiplier=5,percent=true}},
 [0x414] = {{stat="Iron Tempest:DMG:", offset=1,multiplier=5,percent=true}},
 [0x415] = {{stat="Sturmwind:DMG:", offset=1,multiplier=5,percent=true}},
 [0x416] = {{stat="Keen Edge:DMG:", offset=1,multiplier=5,percent=true}},
 [0x417] = {{stat="Steel Cyclone:DMG:", offset=1,multiplier=5,percent=true}},
 [0x418] = {{stat="Nightmare Scythe:DMG:", offset=1,multiplier=5,percent=true}},
 [0x419] = {{stat="Spinning Scythe:DMG:", offset=1,multiplier=5,percent=true}},
 [0x41A] = {{stat="Vorpal Scythe:DMG:", offset=1,multiplier=5,percent=true}},
 [0x41B] = {{stat="Spiral Hell:DMG:", offset=1,multiplier=5,percent=true}},
 [0x41C] = {{stat="Leg Sweep:DMG:", offset=1,multiplier=5,percent=true}},
 [0x41D] = {{stat="Skewer:DMG:", offset=1,multiplier=5,percent=true}},
 [0x41E] = {{stat="Vorpal Thrust:DMG:", offset=1,multiplier=5,percent=true}},
 [0x41F] = {{stat="Impulse Drive:DMG:", offset=1,multiplier=5,percent=true}},
 [0x420] = {{stat="Blade: To:DMG:", offset=1,multiplier=5,percent=true}},
 [0x421] = {{stat="Blade: Chi:DMG:", offset=1,multiplier=5,percent=true}},
 [0x422] = {{stat="Blade: Ten:DMG:", offset=1,multiplier=5,percent=true}},
 [0x423] = {{stat="Blade: Ku:DMG:", offset=1,multiplier=5,percent=true}},
 [0x424] = {{stat="Tachi: Goten:DMG:", offset=1,multiplier=5,percent=true}},
 [0x425] = {{stat="Tachi: Jinpu:DMG:", offset=1,multiplier=5,percent=true}},
 [0x426] = {{stat="Tachi: Koki:DMG:", offset=1,multiplier=5,percent=true}},
 [0x427] = {{stat="Tachi: Kasha:DMG:", offset=1,multiplier=5,percent=true}},
 [0x428] = {{stat="Brainshaker:DMG:", offset=1,multiplier=5,percent=true}},
 [0x429] = {{stat="Skullbreaker:DMG:", offset=1,multiplier=5,percent=true}},
 [0x42A] = {{stat="Judgment:DMG:", offset=1,multiplier=5,percent=true}},
 [0x42B] = {{stat="Black Halo:DMG:", offset=1,multiplier=5,percent=true}},
 [0x42C] = {{stat="Rock Crusher:DMG:", offset=1,multiplier=5,percent=true}},
 [0x42D] = {{stat="Shell Crusher:DMG:", offset=1,multiplier=5,percent=true}},
 [0x42E] = {{stat="Full Swing:DMG:", offset=1,multiplier=5,percent=true}},
 [0x42F] = {{stat="Retribution:DMG:", offset=1,multiplier=5,percent=true}},
 [0x430] = {{stat="Dulling Arrow:DMG:", offset=1,multiplier=5,percent=true}},
 [0x431] = {{stat="Blast Arrow:DMG:", offset=1,multiplier=5,percent=true}},
 [0x432] = {{stat="Arching Arrow:DMG:", offset=1,multiplier=5,percent=true}},
 [0x433] = {{stat="Empyreal Arrow:DMG:", offset=1,multiplier=5,percent=true}},
 [0x434] = {{stat="Hot Shot:DMG:", offset=1,multiplier=5,percent=true}},
 [0x435] = {{stat="Split Shot:DMG:", offset=1,multiplier=5,percent=true}},
 [0x436] = {{stat="Sniper Shot:DMG:", offset=1,multiplier=5,percent=true}},
 [0x437] = {{stat="Detonator:DMG:", offset=1,multiplier=5,percent=true}},
 [0x438] = {{stat="Weapon Skill:DMG:", offset=1,multiplier=5,percent=true}},

 [0x480] = {{stat="DEF", offset=1,multiplier=10}},
 [0x481] = {{stat="Evasion", offset=1,multiplier=3}},
 [0x482] = {{stat="Mag. Evasion", offset=1,multiplier=3}},
 [0x483] = {{stat="Phys. dmg. taken", offset=1,multiplier=-2,percent=true}},
 [0x484] = {{stat="Magic dmg. taken", offset=1,multiplier=-2,percent=true}},
 [0x485] = {{stat="Spell interruption rate down", offset=1,multiplier=-2,percent=true}},
 [0x486] = {{stat="Occ. inc. resist. to stat. ailments", offset=1,multiplier=2}},

 [0x4DE] = {{stat="Pet: Phys. dmg. taken", offset=1,multiplier=-2,percent=true}},
 [0x4DF] = {{stat="Pet: Magic dmg. taken", offset=1,multiplier=-2,percent=true}},
 [0x4E0] = {{stat="Enh. Mag. eff. dur. ", offset=1}},
 [0x4E1] = {{stat="Helix eff. dur. ", offset=1}},
 [0x4E2] = {{stat="Indi. eff. dur. ", offset=1}},
 
 [0x4F0] = {{stat="Meditate eff. dur. ", offset=1}},
 
 [0x500] = {{stat='Enhances "Mighty Strikes" effect', offset=0,multiplier=0}},
 [0x501] = {{stat='Enhances "Hundred Fists" effect', offset=0,multiplier=0}},
 [0x502] = {{stat='Enhances "Benediction" effect', offset=0,multiplier=0}},
 [0x503] = {{stat='Enhances "Manafont" effect', offset=0,multiplier=0}},
 [0x504] = {{stat='Enhances "Chainspell" effect', offset=0,multiplier=0}},
 [0x505] = {{stat='Enhances "Perfect Dodge" effect', offset=0,multiplier=0}},
 [0x506] = {{stat='Enhances "Invincible" effect', offset=0,multiplier=0}},
 [0x507] = {{stat='Enhances "Blood Weapon" effect', offset=0,multiplier=0}},
 [0x508] = {{stat='Enhances "Familiar" effect', offset=0,multiplier=0}},
 [0x509] = {{stat='Enhances "Soul Voice" effect', offset=0,multiplier=0}},
 [0x50A] = {{stat='Enhances "Eagle Eye Shot" effect', offset=0,multiplier=0}},
 [0x50B] = {{stat='Enhances "Meikyo Shisui" effect', offset=0,multiplier=0}},
 [0x50C] = {{stat='Enhances "Mijin Gakure" effect', offset=0,multiplier=0}},
 [0x50D] = {{stat='Enhances "Spirit Surge" effect', offset=0,multiplier=0}},
 [0x50E] = {{stat='Enhances "Astral Flow" effect', offset=0,multiplier=0}},
 [0x50F] = {{stat='Enhances "Azure Lore" effect', offset=0,multiplier=0}},
 [0x510] = {{stat='Enhances "Wild Card" effect', offset=0,multiplier=0}},
 [0x511] = {{stat='Enhances "Overdrive" effect', offset=0,multiplier=0}},
 [0x512] = {{stat='Enhances "Trance" effect', offset=0,multiplier=0}},
 [0x513] = {{stat='Enhances "Tabula Rasa" effect', offset=0,multiplier=0}},
 [0x514] = {{stat='Enhances "Bolster" effect', offset=0,multiplier=0}},
 [0x515] = {{stat='Enhances "Elemental Sforzo" effect', offset=0,multiplier=0}},
 
 [0x530] = {{stat='Enhances "Savagery" effect', offset=0,multiplier=0}},
 [0x531] = {{stat='Enhances "Aggressive Aim" effect', offset=0,multiplier=0}},
 [0x532] = {{stat='Enhances "Warrior\'s Charge" effect', offset=0,multiplier=0}},
 [0x533] = {{stat='Enhances "Tomahawk" effect', offset=0,multiplier=0}},

 [0x536] = {{stat='Enhances "Penance" effect', offset=0,multiplier=0}},
 [0x537] = {{stat='Enhances "Formless Strikes" effect', offset=0,multiplier=0}},
 [0x538] = {{stat='Enhances "Invigorate" effect', offset=0,multiplier=0}},
 [0x539] = {{stat='Enhances "Mantra" effect', offset=0,multiplier=0}},

 [0x53C] = {{stat='Enhances "Afflatus Solace" effect', offset=0,multiplier=0}},
 [0x53D] = {{stat='Enhances "Martyr" effect', offset=0,multiplier=0}},
 [0x53E] = {{stat='Enhances "Afflatus Misery" effect', offset=0,multiplier=0}},
 [0x53F] = {{stat='Enhances "Devotion" effect', offset=0,multiplier=0}},
 
 [0x542] = {{stat='Increases Ancient Magic damage and magic burst damage', offset=0,multiplier=0}},
 [0x543] = {{stat='Increases Elemental Magic accuracy', offset=0,multiplier=0}},
 [0x544] = {{stat='Increases Elemental Magic debuff time and potency', offset=0,multiplier=0}},
 [0x545] = {{stat='Increases Aspir absorption amount', offset=0,multiplier=0}},

 [0x548] = {{stat='Enfeebling Magic duration', offset=0,multiplier=0}},
 [0x549] = {{stat='Magic Accuracy', offset=0,multiplier=0}},
 [0x54A] = {{stat='Enhancing Magic duration', offset=0,multiplier=0}},
 [0x54B] = {{stat='Enspell Damage', offset=0,multiplier=0}},
 [0x54C] = {{stat='Accuracy', offset=0,multiplier=0}},
 [0x54D] = {{stat='Immunobreak Chance', offset=0,multiplier=0}},
 
 [0x54E] = {{stat='Enhances "Aura Steal" effect', offset=0,multiplier=0}},
 [0x54F] = {{stat='Enhances "Ambush" effect', offset=0,multiplier=0}},
 [0x550] = {{stat='Enhances "Feint" effect', offset=0,multiplier=0}},
 [0x551] = {{stat='Enhances "Assassin\'s Charge" effect', offset=0,multiplier=0}},
 
 [0x554] = {{stat='Enhances "Iron Will" effect', offset=0,multiplier=0}},
 [0x555] = {{stat='Enhances "Fealty" effect', offset=0,multiplier=0}},
 [0x556] = {{stat='Enhances "Chivalry" effect', offset=0,multiplier=0}},
 [0x557] = {{stat='Enhances "Guardian" effect', offset=0,multiplier=0}},
 
 [0x55A] = {{stat='Enhances "Dark Seal" effect', offset=0,multiplier=0}},
 [0x55B] = {{stat='Enhances "Diabolic Eye" effect', offset=0,multiplier=0}},
 [0x55C] = {{stat='Enhances "Muted Soul" effect', offset=0,multiplier=0}},
 [0x55D] = {{stat='Enhances "Desperate Blows" effect', offset=0,multiplier=0}},
 
 [0x560] = {{stat='Enhances "Killer Instinct" effect', offset=0,multiplier=0}},
 [0x561] = {{stat='Enhances "Feral Howl" effect', offset=0,multiplier=0}},
 [0x562] = {{stat='Enhances "Beast Affinity" effect', offset=0,multiplier=0}},
 [0x563] = {{stat='Enhances "Beast Healer" effect', offset=0,multiplier=0}},
 
 [0x566] = {{stat='Enhances "Con Anima" effect', offset=0,multiplier=0}},
 [0x567] = {{stat='Enhances "Troubadour" effect', offset=0,multiplier=0}},
 [0x568] = {{stat='Enhances "Con Brio" effect', offset=0,multiplier=0}},
 [0x569] = {{stat='Enhances "Nightingale" effect', offset=0,multiplier=0}},
 
 [0x56C] = {{stat='Enhances "Recycle" effect', offset=0,multiplier=0}},
 [0x56D] = {{stat='Enhances "Snapshot" effect', offset=0,multiplier=0}},
 [0x56E] = {{stat='Enhances "Flashy Shot" effect', offset=0,multiplier=0}},
 [0x56F] = {{stat='Enhances "Stealth Shot" effect', offset=0,multiplier=0}},
 
 [0x572] = {{stat='Enhances "Shikikoyo" effect', offset=0,multiplier=0}},
 [0x573] = {{stat='Enhances "Overwhelm" effect', offset=0,multiplier=0}},
 [0x574] = {{stat='Enhances "Blade Bash" effect', offset=0,multiplier=0}},
 [0x575] = {{stat='Enhances "Ikishoten" effect', offset=0,multiplier=0}},
 
 [0x578] = {{stat='Enhances "Yonin" and "Innin" effect', offset=0,multiplier=0}},
 [0x579] = {{stat='Enhances "Sange" effect', offset=0,multiplier=0}},
 [0x57A] = {{stat='Enh. "Ninja Tool Expertise" effect', offset=0,multiplier=0}},
 [0x57B] = {{stat='Enh. Ninj. Mag. Acc/Cast Time Red.', offset=0,multiplier=0}},
 
 [0x57E] = {{stat='Enhances "Deep Breathing" effect', offset=0,multiplier=0}},
 [0x57F] = {{stat='Enhances "Angon" effect', offset=0,multiplier=0}},
 [0x580] = {{stat='Enhances "Strafe" effect', offset=0,multiplier=0}},
 [0x581] = {{stat='Enhances "Empathy" effect', offset=0,multiplier=0}},
 
 [0x584] = {{stat='Reduces Sp. "Blood Pact" MP cost', offset=0,multiplier=0}},
 [0x585] = {{stat='Inc. Sp. "Blood Pact" magic burst dmg.', offset=0,multiplier=0}},
 [0x586] = {{stat='Increases Sp. "Blood Pact" accuracy', offset=0,multiplier=0}},
 [0x587] = {{stat='Inc. Sp. "Blood Pact" magic crit. dmg.', offset=0,multiplier=0}},
 
 [0x58A] = {{stat='Enhances "Convergence" effect', offset=0,multiplier=0}},
 [0x58B] = {{stat='Enhances "Enchainment" effect', offset=0,multiplier=0}},
 [0x58C] = {{stat='Enhances "Assimilation" effect', offset=0,multiplier=0}},
 [0x58D] = {{stat='Enhances "Diffusion" effect', offset=0,multiplier=0}},
 
 [0x590] = {{stat='Enhances "Winning Streak" effect', offset=0,multiplier=0}},
 [0x591] = {{stat='Enhances "Loaded Deck" effect', offset=0,multiplier=0}},
 [0x592] = {{stat='Enhances "Fold" effect', offset=0,multiplier=0}},
 [0x593] = {{stat='Enhances "Snake Eye" effect', offset=0,multiplier=0}},
 
 [0x596] = {{stat='Enhances "Optimization" effect', offset=0,multiplier=0}},
 [0x597] = {{stat='Enhances "Fine-Tuning" effect', offset=0,multiplier=0}},
 [0x598] = {{stat='Enhances "Ventriloquy" effect', offset=0,multiplier=0}},
 [0x599] = {{stat='Enhances "Role Reversal" effect', offset=0,multiplier=0}},
 
 [0x59C] = {{stat='Enhances "No Foot Rise" effect', offset=0,multiplier=0}},
 [0x59D] = {{stat='Enhances "Fan Dance" effect', offset=0,multiplier=0}},
 [0x59E] = {{stat='Enhances "Saber Dance" effect', offset=0,multiplier=0}},
 [0x59F] = {{stat='Enhances "Closed Position" effect', offset=0,multiplier=0}},
 
 [0x5A2] = {{stat='Enh. "Altruism" and "Focalization"', offset=0,multiplier=0}},
 [0x5A3] = {{stat='Enhances "Enlightenment" effect', offset=0,multiplier=0}},
 [0x5A4] = {{stat='Enh. "Tranquility" and "Equanimity"', offset=0,multiplier=0}},
 [0x5A5] = {{stat='Enhances "Stormsurge" effect', offset=0,multiplier=0}},
 
 [0x5A8] = {{stat='Enhances "Mending Halation" effect', offset=0,multiplier=0}},
 [0x5A9] = {{stat='Enhances "Radial Arcana" effect', offset=0,multiplier=0}},
 [0x5AA] = {{stat='Enhances "Curative Recantation" effect', offset=0,multiplier=0}},
 [0x5AB] = {{stat='Enhances "Primeval Zeal" effect', offset=0,multiplier=0}},
 
 [0x5AE] = {{stat='Enhances "Battuta" effect', offset=0,multiplier=0}},
 [0x5AF] = {{stat='Enhances "Rayke" effect', offset=0,multiplier=0}},
 [0x5B0] = {{stat='Enhances "Inspire" effect', offset=0,multiplier=0}},
 [0x5B1] = {{stat='Enhances "Sleight of Sword" effect', offset=0,multiplier=0}},

 [0x5C0] = {{stat="Parrying rate", offset=1,percent=true}},
 
 [0x600] = {{stat="Backhand Blow:DMG:", offset=1,multiplier=5,percent=true}},
 [0x601] = {{stat="Spinning Attack:DMG:", offset=1,multiplier=5,percent=true}},
 [0x602] = {{stat="Howling Fist:DMG:", offset=1,multiplier=5,percent=true}},
 [0x603] = {{stat="Dragon Kick:DMG:", offset=1,multiplier=5,percent=true}},
 [0x604] = {{stat="Viper Bite:DMG:", offset=1,multiplier=5,percent=true}},
 [0x605] = {{stat="Shadowstitch:DMG:", offset=1,multiplier=5,percent=true}},
 [0x606] = {{stat="Cyclone:DMG:", offset=1,multiplier=5,percent=true}},
 [0x607] = {{stat="Evisceration:DMG:", offset=1,multiplier=5,percent=true}},
 [0x608] = {{stat="Burning Blade:DMG:", offset=1,multiplier=5,percent=true}},
 [0x609] = {{stat="Shining Blade:DMG:", offset=1,multiplier=5,percent=true}},
 [0x60A] = {{stat="Circle Blade:DMG:", offset=1,multiplier=5,percent=true}},
 [0x60B] = {{stat="Savage Blade:DMG:", offset=1,multiplier=5,percent=true}},
 [0x60C] = {{stat="Freezebite:DMG:", offset=1,multiplier=5,percent=true}},
 [0x60D] = {{stat="Shockwave:DMG:", offset=1,multiplier=5,percent=true}},
 [0x60E] = {{stat="Ground Strike:DMG:", offset=1,multiplier=5,percent=true}},
 [0x60F] = {{stat="Sickle Moon:DMG:", offset=1,multiplier=5,percent=true}},
 [0x610] = {{stat="Gale Axe:DMG:", offset=1,multiplier=5,percent=true}},
 [0x611] = {{stat="Spinning Axe:DMG:", offset=1,multiplier=5,percent=true}},
 [0x612] = {{stat="Calamity:DMG:", offset=1,multiplier=5,percent=true}},
 [0x613] = {{stat="Decimation:DMG:", offset=1,multiplier=5,percent=true}},
 [0x614] = {{stat="Iron Tempest:DMG:", offset=1,multiplier=5,percent=true}},
 [0x615] = {{stat="Sturmwind:DMG:", offset=1,multiplier=5,percent=true}},
 [0x616] = {{stat="Keen Edge:DMG:", offset=1,multiplier=5,percent=true}},
 [0x617] = {{stat="Steel Cyclone:DMG:", offset=1,multiplier=5,percent=true}},
 [0x618] = {{stat="Nightmare Scythe:DMG:", offset=1,multiplier=5,percent=true}},
 [0x619] = {{stat="Spinning Scythe:DMG:", offset=1,multiplier=5,percent=true}},
 [0x61A] = {{stat="Vorpal Scythe:DMG:", offset=1,multiplier=5,percent=true}},
 [0x61B] = {{stat="Spiral Hell:DMG:", offset=1,multiplier=5,percent=true}},
 [0x61C] = {{stat="Leg Sweep:DMG:", offset=1,multiplier=5,percent=true}},
 [0x61D] = {{stat="Skewer:DMG:", offset=1,multiplier=5,percent=true}},
 [0x61E] = {{stat="Vorpal Thrust:DMG:", offset=1,multiplier=5,percent=true}},
 [0x61F] = {{stat="Impulse Drive:DMG:", offset=1,multiplier=5,percent=true}},
 [0x620] = {{stat="Blade: To:DMG:", offset=1,multiplier=5,percent=true}},
 [0x621] = {{stat="Blade: Chi:DMG:", offset=1,multiplier=5,percent=true}},
 [0x622] = {{stat="Blade: Ten:DMG:", offset=1,multiplier=5,percent=true}},
 [0x623] = {{stat="Blade: Ku:DMG:", offset=1,multiplier=5,percent=true}},
 [0x624] = {{stat="Tachi: Goten:DMG:", offset=1,multiplier=5,percent=true}},
 [0x625] = {{stat="Tachi: Jinpu:DMG:", offset=1,multiplier=5,percent=true}},
 [0x626] = {{stat="Tachi: Koki:DMG:", offset=1,multiplier=5,percent=true}},
 [0x627] = {{stat="Tachi: Kasha:DMG:", offset=1,multiplier=5,percent=true}},
 [0x628] = {{stat="Brainshaker:DMG:", offset=1,multiplier=5,percent=true}},
 [0x629] = {{stat="Skullbreaker:DMG:", offset=1,multiplier=5,percent=true}},
 [0x62A] = {{stat="Judgment:DMG:", offset=1,multiplier=5,percent=true}},
 [0x62B] = {{stat="Black Halo:DMG:", offset=1,multiplier=5,percent=true}},
 [0x62C] = {{stat="Rock Crusher:DMG:", offset=1,multiplier=5,percent=true}},
 [0x62D] = {{stat="Shell Crusher:DMG:", offset=1,multiplier=5,percent=true}},
 [0x62E] = {{stat="Full Swing:DMG:", offset=1,multiplier=5,percent=true}},
 [0x62F] = {{stat="Retribution:DMG:", offset=1,multiplier=5,percent=true}},
 [0x630] = {{stat="Dulling Arrow:DMG:", offset=1,multiplier=5,percent=true}},
 [0x631] = {{stat="Blast Arrow:DMG:", offset=1,multiplier=5,percent=true}},
 [0x632] = {{stat="Arching Arrow:DMG:", offset=1,multiplier=5,percent=true}},
 [0x633] = {{stat="Empyreal Arrow:DMG:", offset=1,multiplier=5,percent=true}},
 [0x634] = {{stat="Hot Shot:DMG:", offset=1,multiplier=5,percent=true}},
 [0x635] = {{stat="Split Shot:DMG:", offset=1,multiplier=5,percent=true}},
 [0x636] = {{stat="Sniper Shot:DMG:", offset=1,multiplier=5,percent=true}},
 [0x637] = {{stat="Detonator:DMG:", offset=1,multiplier=5,percent=true}},
 [0x638] = {{stat="Weapon Skill:DMG:", offset=1,multiplier=5,percent=true}},
 
 [0x700] = {{stat="Pet: STR", offset=1}},
 [0x701] = {{stat="Pet: DEX", offset=1}},
 [0x702] = {{stat="Pet: VIT", offset=1}},
 [0x703] = {{stat="Pet: AGI", offset=1}},
 [0x704] = {{stat="Pet: INT", offset=1}},
 [0x705] = {{stat="Pet: MND", offset=1}},
 [0x706] = {{stat="Pet: CHR", offset=1}},
 [0x707] = {{stat="Pet: STR", offset=1,multiplier=-1}},
 [0x708] = {{stat="Pet: DEX", offset=1,multiplier=-1}},
 [0x709] = {{stat="Pet: VIT", offset=1,multiplier=-1}},
 [0x70A] = {{stat="Pet: AGI", offset=1,multiplier=-1}},
 [0x70B] = {{stat="Pet: INT", offset=1,multiplier=-1}},
 [0x70C] = {{stat="Pet: MND", offset=1,multiplier=-1}},
 [0x70D] = {{stat="Pet: CHR", offset=1,multiplier=-1}},
 [0x70E] = {{stat="Pet: STR", offset=1},{stat="Pet: DEX", offset=1},{stat="Pet: VIT", offset=1}},
 [0x70F] = {{stat="Pet:", offset=0,multiplier=0}},
 [0x710] = {{stat="Pet:", offset=0,multiplier=0}},
 [0x711] = {{stat="Pet:", offset=0,multiplier=0}},
 [0x712] = {{stat="Pet:", offset=0,multiplier=0}},
 [0x713] = {{stat="Pet:", offset=0,multiplier=0}},
 [0x714] = {{stat="Pet:", offset=0,multiplier=0}},
 [0x715] = {{stat="Pet:", offset=0,multiplier=0}},
 [0x716] = {{stat="Pet:", offset=0,multiplier=0}},
 [0x717] = {{stat="Pet:", offset=0,multiplier=0}},
 [0x718] = {{stat="Pet:", offset=0,multiplier=0}},
 [0x719] = {{stat="Pet:", offset=0,multiplier=0}},
 [0x71A] = {{stat="Pet:", offset=0,multiplier=0}},
 [0x71B] = {{stat="Pet:", offset=0,multiplier=0}},
 [0x71C] = {{stat="Pet:", offset=0,multiplier=0}},
 [0x71D] = {{stat="Pet:", offset=0,multiplier=0}},
 [0x71E] = {{stat="Pet:", offset=0,multiplier=0}},
 [0x71F] = {{stat="Pet:", offset=0,multiplier=0}},
 
 [0x7FF] = {{stat='???', offset=0}},
}

return M
