-- Spells to exclude from the "Show All" expanded spell list.
-- These exist in the horizonspells.lua database but are not available on HorizonXI.
-- Add spell names here (exact match) to hide them from the dropdown.

return {
    -- ── Black Magic ──────────────────────────────────────────

    -- Tier V/VI nukes (post-75)
    'Fire V',
    'Fire VI',
    'Blizzard V',
    'Blizzard VI',
    'Aero V',
    'Aero VI',
    'Stone V',
    'Stone VI',
    'Thunder V',
    'Thunder VI',
    'Water V',
    'Water VI',

    -- -ga IV/V (post-75)
    'Firaga IV',
    'Firaga V',
    'Blizzaga IV',
    'Blizzaga V',
    'Aeroga IV',
    'Aeroga V',
    'Stonega IV',
    'Stonega V',
    'Thundaga IV',
    'Thundaga V',
    'Waterga IV',
    'Waterga V',

    -- -ja nukes
    'Firaja',
    'Blizzaja',
    'Aeroja',
    'Stoneja',
    'Thundaja',
    'Waterja',

    -- -ra nukes
    'Fira',
    'Fira II',
    'Fira III',
    'Blizzara',
    'Blizzara II',
    'Blizzara III',
    'Aera',
    'Aera II',
    'Aera III',
    'Stonera',
    'Stonera II',
    'Stonera III',
    'Thundara',
    'Thundara II',
    'Thundara III',
    'Watera',
    'Watera II',
    'Watera III',

    -- Ancient Magic II
    'Flare II',
    'Freeze II',
    'Tornado II',
    'Quake II',
    'Burst II',
    'Flood II',

    -- DoT / enfeeble upgrades
    'Bio III',
    'Bio IV',
    'Bio V',
    'Poison III',
    'Poison IV',
    'Poison V',
    'Poisonga II',
    'Poisonga III',
    'Poisonga IV',
    'Poisonga V',
    'Blind II',
    'Blindga',
    'Bindga',
    'Breakga',
    'Graviga',
    'Gravity II',
    'Curse',
    'Virus',

    -- Absorb extras
    'Absorb-ACC',
    'Absorb-Attri',
    'Absorb-TP',

    -- Aspir / Drain upgrades
    'Aspir II',
    'Aspir III',
    'Drain II',
    'Drain III',

    -- Scholar Helix
    'Anemohelix',
    'Anemohelix II',
    'Cryohelix',
    'Cryohelix II',
    'Geohelix',
    'Geohelix II',
    'Hydrohelix',
    'Hydrohelix II',
    'Ionohelix',
    'Ionohelix II',
    'Luminohelix',
    'Luminohelix II',
    'Noctohelix',
    'Noctohelix II',
    'Pyrohelix',
    'Pyrohelix II',

    -- Misc post-era
    'Break',
    'Comet',
    'Death',
    'Dispelga',
    'Distract',
    'Distract II',
    'Distract III',
    'Dread Spikes',
    'Endark',
    'Endark II',
    'Frazzle',
    'Frazzle II',
    'Frazzle III',
    'Impact',
    'Kaustra',
    'Klimaform',
    'Meteor',
    'Meteor II',
    'Retrace',
    'Tractor II',

    -- ── White Magic ──────────────────────────────────────────

    -- Post-75 cures / healing
    'Cure VI',
    'Curaga V',
    'Cura',
    'Cura II',
    'Cura III',
    'Full Cure',
    'Arise',
    'Esuna',
    'Sacrifice',
    'Adloquium',

    -- Post-75 enhancing
    'Haste II',
    'Hastega',
    'Refresh II',
    'Refresh III',
    'Regen IV',
    'Regen V',
    'Protect V',
    'Shell V',
    'Phalanx',
    'Phalanx II',
    'Flurry',
    'Flurry II',
    'Temper',
    'Temper II',
    'Reprisal',
    'Crusade',
    'Foil',
    'Embrava',
    'Auspice',
    'Animus Augeo',
    'Animus Minuo',
    'Inundation',

    -- En-spells
    'Enaero',
    'Enaero II',
    'Enblizzard',
    'Enblizzard II',
    'Enfire',
    'Enfire II',
    'Enlight II',
    'Enstone',
    'Enstone II',
    'Enthunder',
    'Enthunder II',
    'Enwater',
    'Enwater II',

    -- Boost / Gain
    'Boost-AGI',
    'Boost-CHR',
    'Boost-DEX',
    'Boost-INT',
    'Boost-MND',
    'Boost-STR',
    'Boost-VIT',
    'Gain-AGI',
    'Gain-CHR',
    'Gain-DEX',
    'Gain-INT',
    'Gain-MND',
    'Gain-STR',
    'Gain-VIT',

    -- Storms (Scholar)
    'Aurorastorm',
    'Aurorastorm II',
    'Firestorm',
    'Firestorm II',
    'Hailstorm',
    'Hailstorm II',
    'Rainstorm',
    'Rainstorm II',
    'Sandstorm',
    'Sandstorm II',
    'Thunderstorm',
    'Thunderstorm II',
    'Voidstorm',
    'Voidstorm II',
    'Windstorm',
    'Windstorm II',

    -- Enfeeble upgrades
    'Addle',
    'Addle II',
    'Paralyze II',
    'Paralyga',
    'Slow II',
    'Slowga',
    'Silencega',
    'Repose',

    -- Banish / Dia upgrades
    'Banish IV',
    'Banish V',
    'Banishga III',
    'Banishga IV',
    'Banishga V',
    'Dia III',
    'Dia IV',
    'Dia V',
    'Diaga II',
    'Diaga III',
    'Diaga IV',
    'Diaga V',

    -- Bar-spell extras
    'Baramnesia',
    'Baramnesra',

    -- Recall spells
    'Recall-Jugner',
    'Recall-Meriph',
    'Recall-Pashh',

    -- Misc post-era white magic
    'Holy II',
    'Reraise IV',

    -- ── Songs (Bard) ─────────────────────────────────────────

    'Adventurer\'s Dirge',
    'Army\'s Paeon VI',
    'Army\'s Paeon VII',
    'Army\'s Paeon VIII',
    'Cactuar Fugue',
    'Chocobo Hum',
    'Dark Carol II',
    'Dark Threnody II',
    'Devotee Serenade',
    'Earth Carol II',
    'Earth Threnody II',
    'Fire Carol II',
    'Fire Threnody II',
    'Foe Lullaby II',
    'Foe Requiem VII',
    'Foe Requiem VIII',
    'Foe Sirvente',
    'Honor March',
    'Horde Lullaby II',
    'Ice Carol II',
    'Ice Threnody II',
    'Jester\'s Operetta',
    'Knight\'s Minne V',
    'Light Carol II',
    'Light Threnody II',
    'Lightning Carol II',
    'Ltng. Threnody II',
    'Mage\'s Ballad III',
    'Massacre Elegy',
    'Pining Nocturne',
    'Protected Aria',
    'Raptor Mazurka',
    'Sentinel\'s Scherzo',
    'Valor Minuet V',
    'Water Carol II',
    'Water Threnody II',
    'Wind Carol II',
    'Wind Threnody II',

    -- ── Ninjutsu ─────────────────────────────────────────────

    -- :San tier (post-75)
    'Doton: San',
    'Huton: San',
    'Hyoton: San',
    'Katon: San',
    'Raiton: San',
    'Suiton: San',
    'Kurayami: San',
    'Hojo: San',
    'Dokumori: San',
    'Jubaku: San',
    'Utsusemi: San',

    -- :Ni tier not on Horizon
    'Dokumori: Ni',
    'Jubaku: Ni',

    -- Misc post-era
    'Aisha: Ichi',
    'Gekka: Ichi',
    'Kakka: Ichi',
    'Migawari: Ichi',
    'Monomi: Ichi',
    'Myoshu: Ichi',
    'Yain: Ichi',
    'Yurin: Ichi',

    -- ── Summoning ─────────────────────────────────────────────

    -- Avatars not yet on Horizon
    'Alexander',
    'Atomos',
    'Cait Sith',
    'Odin',
    'Siren',
}
