--[[
  XIUI-only overlays for blood pact rows (Horizon): status labels, corner icons, astral flow.
  Retail `petregistry` stays name + avatars; merge these in `petregistry.GetBloodPactByName`.
  Keys = English pact name (same as horizon_bloodpacts / petregistry).
]]
return {
    -- Rage
    ['Inferno'] = { requiresFlow = true },
    ['Diamond Dust'] = { requiresFlow = true },
    ['Aerial Blast'] = { requiresFlow = true },
    ['Rock Throw'] = { status = 'Slow' },
    ['Rock Buster'] = { status = 'Bind' },
    ['Megalith Throw'] = { status = 'Slow' },
    ['Mountain Buster'] = { status = 'Bind' },
    ['Geocrush'] = { status = 'Stun' },
    ['Earthen Fury'] = { requiresFlow = true },
    ['Shock Strike'] = { status = 'Stun' },
    ['Thunderspark'] = { status = 'Paralyze' },
    ['Chaotic Strike'] = { status = 'Stun' },
    ['Judgment Bolt'] = { requiresFlow = true },
    ['Tail Whip'] = { status = 'Weight' },
    ['Tidal Wave'] = { requiresFlow = true },
    ['Moonlit Charge'] = { status = 'Blind' },
    ['Crescent Fang'] = { status = 'Paralyze' },
    ['Howling Moon'] = { requiresFlow = true },
    ['Camisado'] = { status = 'Knockback' },
    ['Ruinous Omen'] = { requiresFlow = true },
    ['Poison Nails'] = { status = 'Poison' },
    ['Searing Light'] = { requiresFlow = true },
    ['Zantetsuken'] = { requiresFlow = true },
    -- Ward
    ['Poison Ruby'] = { status = 'Poison' },
    ['Shining Ruby'] = { statusCornerIcon = 'assets/status/HD/41.png' },
    ['Glittering Ruby'] = { statusCornerIcon = 'assets/status/Tetsouou/308.png' },
    ['Crimson Howl'] = { statusCornerIcon = 'assets/status/Tetsouou/549.png' },
    ['Frost Armor'] = { statusCornerIcon = 'assets/status/Tetsouou/35.png' },
    ['Sleepga'] = { status = 'Sleep', statusCornerIcon = 'assets/status/Tetsouou/19.png' },
    ['Diamond Storm'] = { status = 'Evasion Down' },
    ['Whispering Wind'] = { statusCornerIcon = 'assets/status/Tetsouou/78.png' },
    ['Hastega'] = { statusCornerIcon = 'assets/status/Tetsouou/580.png' },
    ['Aerial Armor'] = { statusCornerIcon = 'assets/status/Tetsouou/36.png' },
    ['Earthen Ward'] = { statusCornerIcon = 'assets/status/HD/37.png' },
    ['Rolling Thunder'] = { statusCornerIcon = 'assets/status/XIView/98.png' },
    ['Lightning Armor'] = { statusCornerIcon = 'assets/status/XIView/38.png' },
    ['Slowga'] = { status = 'Slow' },
    ['Spring Water'] = { statusCornerIcon = 'assets/status/Tetsouou/43.png' },
    ['Ecliptic Growl'] = { statusCornerIcon = 'assets/status/Tetsouou/515.png' },
    ['Ecliptic Howl'] = { statusCornerIcon = 'assets/status/Tetsouou/90.png' },
    ['Lunar Cry'] = { status = 'Accuracy Down', statusCornerIcon = 'assets/status/Tetsouou/562.png' },
    ['Lunar Roar'] = { statusCornerIcon = 'assets/hotbar/custom/Enfeebling Magic/Dispel.png' },
    ['Somnolence'] = { status = 'Weight' },
    ['Nightmare'] = { status = 'Sleep' },
    ['Perfect Defense'] = { requiresFlow = true },
}
