-- Retail skillchain properties (shared base). Horizon loads this table, then
-- applies modules/hotbar/database/skillchain_horizon.lua for property diffs,
-- missing 70-cap Blood Pacts, extra BLU, and NPC weaponskills.
-- WS/BLU/pet data ported from LandSandBoat SQL; SCH/immanence/JA/PUP match Chains-Horizon.
local skills = {};

skills[3] = {
 [1] = {en='Combo',skillchain={'Impaction'}},
 [2] = {en='Shoulder Tackle',skillchain={'Reverberation','Impaction'}},
 [3] = {en='One Inch Punch',skillchain={'Compression'}},
 [4] = {en='Backhand Blow',skillchain={'Detonation'}},
 [5] = {en='Raging Fists',skillchain={'Impaction'}},
 [6] = {en='Spinning Attack',skillchain={'Liquefaction','Impaction'}},
 [7] = {en='Howling Fist',skillchain={'Transfixion','Impaction'}},
 [8] = {en='Dragon Kick',skillchain={'Fragmentation'}},
 [9] = {en='Asuran Fists',skillchain={'Gravitation','Liquefaction'}},
 [10] = {en='Final Heaven',skillchain={'Light','Fusion'}},
 [11] = {en='Ascetic\'s Fury',skillchain={'Fusion','Transfixion'}},
 [12] = {en='Stringing Pummel',skillchain={'Gravitation','Liquefaction'}},
 [13] = {en='Tornado Kick',skillchain={'Induration','Impaction','Detonation'}},
 [14] = {en='Victory Smite',skillchain={'Light','Fragmentation'}},
 [15] = {en='Shijin Spiral',skillchain={'Fusion','Reverberation'}},
 [16] = {en='Wasp Sting',skillchain={'Scission'}},
 [17] = {en='Viper Bite',skillchain={'Scission'}},
 [18] = {en='Shadowstitch',skillchain={'Reverberation'}},
 [19] = {en='Gust Slash',skillchain={'Detonation'}},
 [20] = {en='Cyclone',skillchain={'Detonation','Impaction'}},
 [23] = {en='Dancing Edge',skillchain={'Scission','Detonation'}},
 [24] = {en='Shark Bite',skillchain={'Fragmentation'}},
 [25] = {en='Evisceration',skillchain={'Gravitation','Transfixion'}},
 [26] = {en='Mercy Stroke',skillchain={'Darkness','Gravitation'}},
 [27] = {en='Mandalic Stab',skillchain={'Fusion','Compression'}},
 [28] = {en='Mordant Rime',skillchain={'Fragmentation','Distortion'}},
 [29] = {en='Pyrrhic Kleos',skillchain={'Distortion','Scission'}},
 [30] = {en='Aeolian Edge',skillchain={'Scission','Detonation','Impaction'}},
 [31] = {en='Rudra\'s Storm',skillchain={'Darkness','Distortion'}},
 [32] = {en='Fast Blade',skillchain={'Scission'}},
 [33] = {en='Burning Blade',skillchain={'Liquefaction'}},
 [34] = {en='Red Lotus Blade',skillchain={'Liquefaction','Detonation'}},
 [35] = {en='Flat Blade',skillchain={'Impaction'}},
 [36] = {en='Shining Blade',skillchain={'Scission'}},
 [37] = {en='Seraph Blade',skillchain={'Scission'}},
 [38] = {en='Circle Blade',skillchain={'Reverberation','Impaction'}},
 [40] = {en='Vorpal Blade',skillchain={'Scission','Impaction'}},
 [41] = {en='Swift Blade',skillchain={'Gravitation'}},
 [42] = {en='Savage Blade',skillchain={'Fragmentation','Scission'}},
 [43] = {en='Knights of Round',skillchain={'Light','Fusion'}},
 [44] = {en='Death Blossom',skillchain={'Fragmentation','Distortion'}},
 [45] = {en='Atonement',skillchain={'Fusion','Reverberation'}},
 [46] = {en='Expiacion',skillchain={'Distortion','Scission'}},
 [48] = {en='Hard Slash',skillchain={'Scission'}},
 [49] = {en='Power Slash',skillchain={'Transfixion'}},
 [50] = {en='Frostbite',skillchain={'Induration'}},
 [51] = {en='Freezebite',skillchain={'Induration','Detonation'}},
 [52] = {en='Shockwave',skillchain={'Reverberation'}},
 [53] = {en='Crescent Moon',skillchain={'Scission'}},
 [54] = {en='Sickle Moon',skillchain={'Scission','Impaction'}},
 [55] = {en='Spinning Slash',skillchain={'Fragmentation'}},
 [56] = {en='Ground Strike',skillchain={'Fragmentation','Distortion'}},
 [57] = {en='Scourge',skillchain={'Light','Fusion'}},
 [58] = {en='Herculean Slash',skillchain={'Induration','Impaction','Detonation'}},
 [59] = {en='Torcleaver',skillchain={'Light','Distortion'}},
 [60] = {en='Resolution',skillchain={'Fragmentation','Scission'}},
 [61] = {en='Dimidiation',skillchain={'Light','Fragmentation'}},
 [64] = {en='Raging Axe',skillchain={'Detonation','Impaction'}},
 [65] = {en='Smash Axe',skillchain={'Induration','Reverberation'}},
 [66] = {en='Gale Axe',skillchain={'Detonation'}},
 [67] = {en='Avalanche Axe',skillchain={'Scission','Impaction'}},
 [68] = {en='Spinning Axe',skillchain={'Liquefaction','Scission','Impaction'}},
 [69] = {en='Rampage',skillchain={'Scission'}},
 [70] = {en='Calamity',skillchain={'Scission','Impaction'}},
 [71] = {en='Mistral Axe',skillchain={'Fusion'}},
 [72] = {en='Decimation',skillchain={'Fusion','Reverberation'}},
 [73] = {en='Onslaught',skillchain={'Darkness','Gravitation'}},
 [74] = {en='Primal Rend',skillchain={'Gravitation','Reverberation'}},
 [75] = {en='Bora Axe',skillchain={'Scission','Detonation'}},
 [76] = {en='Cloudsplitter',skillchain={'Darkness','Fragmentation'}},
 [77] = {en='Ruinator',skillchain={'Distortion','Detonation'}},
 [80] = {en='Shield Break',skillchain={'Impaction'}},
 [81] = {en='Iron Tempest',skillchain={'Scission'}},
 [82] = {en='Sturmwind',skillchain={'Reverberation','Scission'}},
 [83] = {en='Armor Break',skillchain={'Impaction'}},
 [84] = {en='Keen Edge',skillchain={'Compression'}},
 [85] = {en='Weapon Break',skillchain={'Impaction'}},
 [86] = {en='Raging Rush',skillchain={'Induration','Reverberation'}},
 [87] = {en='Full Break',skillchain={'Distortion'}},
 [88] = {en='Steel Cyclone',skillchain={'Distortion','Detonation'}},
 [89] = {en='Metatron Torment',skillchain={'Light','Fusion'}},
 [90] = {en='King\'s Justice',skillchain={'Fragmentation','Scission'}},
 [91] = {en='Fell Cleave',skillchain={'Scission','Detonation','Impaction'}},
 [92] = {en='Ukko\'s Fury',skillchain={'Light','Fragmentation'}},
 [93] = {en='Upheaval',skillchain={'Fusion','Compression'}},
 [96] = {en='Slice',skillchain={'Scission'}},
 [97] = {en='Dark Harvest',skillchain={'Reverberation'}},
 [98] = {en='Shadow of Death',skillchain={'Induration','Reverberation'}},
 [99] = {en='Nightmare Scythe',skillchain={'Compression','Scission'}},
 [100] = {en='Spinning Scythe',skillchain={'Reverberation','Scission'}},
 [101] = {en='Vorpal Scythe',skillchain={'Transfixion','Scission'}},
 [102] = {en='Guillotine',skillchain={'Induration'}},
 [103] = {en='Cross Reaper',skillchain={'Distortion'}},
 [104] = {en='Spiral Hell',skillchain={'Distortion','Scission'}},
 [105] = {en='Catastrophe',skillchain={'Darkness','Gravitation'}},
 [106] = {en='Insurgency',skillchain={'Fusion','Compression'}},
 [107] = {en='Infernal Scythe',skillchain={'Compression','Reverberation'}},
 [108] = {en='Quietus',skillchain={'Darkness','Distortion'}},
 [109] = {en='Entropy',skillchain={'Gravitation','Reverberation'}},
 [112] = {en='Double Thrust',skillchain={'Transfixion'}},
 [113] = {en='Thunder Thrust',skillchain={'Transfixion','Impaction'}},
 [114] = {en='Raiden Thrust',skillchain={'Transfixion','Impaction'}},
 [115] = {en='Leg Sweep',skillchain={'Impaction'}},
 [116] = {en='Penta Thrust',skillchain={'Compression'}},
 [117] = {en='Vorpal Thrust',skillchain={'Reverberation','Transfixion'}},
 [118] = {en='Skewer',skillchain={'Transfixion','Impaction'}},
 [119] = {en='Wheeling Thrust',skillchain={'Fusion'}},
 [120] = {en='Impulse Drive',skillchain={'Gravitation','Induration'}},
 [121] = {en='Geirskogul',skillchain={'Light','Distortion'}},
 [122] = {en='Drakesbane',skillchain={'Fusion','Transfixion'}},
 [123] = {en='Sonic Thrust',skillchain={'Transfixion','Scission'}},
 [124] = {en='Camlann\'s Torment',skillchain={'Light','Fragmentation'}},
 [125] = {en='Stardiver',skillchain={'Gravitation','Transfixion'}},
 [128] = {en='Blade: Rin',skillchain={'Transfixion'}},
 [129] = {en='Blade: Retsu',skillchain={'Scission'}},
 [130] = {en='Blade: Teki',skillchain={'Reverberation'}},
 [131] = {en='Blade: To',skillchain={'Induration','Detonation'}},
 [132] = {en='Blade: Chi',skillchain={'Transfixion','Impaction'}},
 [133] = {en='Blade: Ei',skillchain={'Compression'}},
 [134] = {en='Blade: Jin',skillchain={'Detonation','Impaction'}},
 [135] = {en='Blade: Ten',skillchain={'Gravitation'}},
 [136] = {en='Blade: Ku',skillchain={'Gravitation','Transfixion'}},
 [137] = {en='Blade: Metsu',skillchain={'Darkness','Fragmentation'}},
 [138] = {en='Blade: Kamu',skillchain={'Fragmentation','Compression'}},
 [139] = {en='Blade: Yu',skillchain={'Reverberation','Scission'}},
 [140] = {en='Blade: Hi',skillchain={'Darkness','Gravitation'}},
 [141] = {en='Blade: Shun',skillchain={'Fusion','Impaction'}},
 [144] = {en='Tachi: Enpi',skillchain={'Transfixion','Scission'}},
 [145] = {en='Tachi: Hobaku',skillchain={'Induration'}},
 [146] = {en='Tachi: Goten',skillchain={'Transfixion','Impaction'}},
 [147] = {en='Tachi: Kagero',skillchain={'Liquefaction'}},
 [148] = {en='Tachi: Jinpu',skillchain={'Scission','Detonation'}},
 [149] = {en='Tachi: Koki',skillchain={'Reverberation','Impaction'}},
 [150] = {en='Tachi: Yukikaze',skillchain={'Induration','Detonation'}},
 [151] = {en='Tachi: Gekko',skillchain={'Distortion','Reverberation'}},
 [152] = {en='Tachi: Kasha',skillchain={'Fusion','Compression'}},
 [153] = {en='Tachi: Kaiten',skillchain={'Light','Fragmentation'}},
 [154] = {en='Tachi: Rana',skillchain={'Gravitation','Induration'}},
 [155] = {en='Tachi: Ageha',skillchain={'Compression','Scission'}},
 [156] = {en='Tachi: Fudo',skillchain={'Light','Distortion'}},
 [157] = {en='Tachi: Shoha',skillchain={'Fragmentation','Compression'}},
 [158] = {en='Tachi: Suikawari',skillchain={'Fusion'}},
 [160] = {en='Shining Strike',skillchain={'Impaction'}},
 [161] = {en='Seraph Strike',skillchain={'Impaction'}},
 [162] = {en='Brainshaker',skillchain={'Reverberation'}},
 [165] = {en='Skullbreaker',skillchain={'Induration','Reverberation'}},
 [166] = {en='True Strike',skillchain={'Impaction','Detonation'}},
 [167] = {en='Judgment',skillchain={'Impaction'}},
 [168] = {en='Hexa Strike',skillchain={'Fusion'}},
 [169] = {en='Black Halo',skillchain={'Fragmentation','Compression'}},
 [170] = {en='Randgrith',skillchain={'Light','Fragmentation'}},
 [172] = {en='Flash Nova',skillchain={'Induration','Reverberation'}},
 [174] = {en='Realmrazer',skillchain={'Fusion','Impaction'}},
 [175] = {en='Exudation',skillchain={'Fragmentation'}},
 [176] = {en='Heavy Swing',skillchain={'Impaction'}},
 [177] = {en='Rock Crusher',skillchain={'Impaction'}},
 [178] = {en='Earth Crusher',skillchain={'Detonation','Impaction'}},
 [179] = {en='Starburst',skillchain={'Compression','Reverberation'}},
 [180] = {en='Sunburst',skillchain={'Compression','Reverberation'}},
 [181] = {en='Shell Crusher',skillchain={'Detonation'}},
 [182] = {en='Full Swing',skillchain={'Liquefaction','Impaction'}},
 [184] = {en='Retribution',skillchain={'Gravitation','Reverberation'}},
 [185] = {en='Gate of Tartarus',skillchain={'Darkness','Distortion'}},
 [186] = {en='Vidohunir',skillchain={'Fragmentation','Distortion'}},
 [187] = {en='Garland of Bliss',skillchain={'Fusion','Reverberation'}},
 [188] = {en='Omniscience',skillchain={'Gravitation','Transfixion'}},
 [189] = {en='Cataclysm',skillchain={'Compression','Reverberation'}},
 [191] = {en='Shattersoul',skillchain={'Gravitation','Induration'}},
 [192] = {en='Flaming Arrow',skillchain={'Liquefaction','Transfixion'}},
 [193] = {en='Piercing Arrow',skillchain={'Reverberation','Transfixion'}},
 [194] = {en='Dulling Arrow',skillchain={'Liquefaction','Transfixion'}},
 [196] = {en='Sidewinder',skillchain={'Reverberation','Transfixion','Detonation'}},
 [197] = {en='Blast Arrow',skillchain={'Induration','Transfixion'}},
 [198] = {en='Arching Arrow',skillchain={'Fusion'}},
 [199] = {en='Empyreal Arrow',skillchain={'Fusion','Transfixion'}},
 [200] = {en='Namas Arrow',skillchain={'Light','Distortion'}},
 [201] = {en='Refulgent Arrow',skillchain={'Reverberation','Transfixion'}},
 [202] = {en='Jishnu\'s Radiance',skillchain={'Light','Fusion'}},
 [203] = {en='Apex Arrow',skillchain={'Fragmentation','Transfixion'}},
 [208] = {en='Hot Shot',skillchain={'Liquefaction','Transfixion'}},
 [209] = {en='Split Shot',skillchain={'Reverberation','Transfixion'}},
 [210] = {en='Sniper Shot',skillchain={'Liquefaction','Transfixion'}},
 [212] = {en='Slug Shot',skillchain={'Reverberation','Transfixion','Detonation'}},
 [213] = {en='Blast Shot',skillchain={'Induration','Transfixion'}},
 [214] = {en='Heavy Shot',skillchain={'Fusion'}},
 [215] = {en='Detonator',skillchain={'Fusion','Transfixion'}},
 [216] = {en='Coronach',skillchain={'Darkness','Fragmentation'}},
 [217] = {en='Trueflight',skillchain={'Fragmentation','Scission'}},
 [218] = {en='Leaden Salute',skillchain={'Gravitation','Transfixion'}},
 [219] = {en='Numbing Shot',skillchain={'Induration','Detonation','Impaction'}},
 [220] = {en='Wildfire',skillchain={'Darkness','Gravitation'}},
 [221] = {en='Last Stand',skillchain={'Fusion','Reverberation'}},
 [224] = {en='Exenterator',skillchain={'Fragmentation','Scission'}},
 [225] = {en='Chant du Cygne',skillchain={'Light','Distortion'}},
 [226] = {en='Requiescat',skillchain={'Gravitation','Scission'}},
 [227] = {en='Knights of Rotund',skillchain={'Light'}},
 [228] = {en='Final Paradise',skillchain={'Light'}},
 [238] = {en='Uriel Blade',skillchain={'Light','Fragmentation'}},
 [239] = {en='Glory Slash',skillchain={'Light','Fusion'}},
};

skills[4] = {
 [519] = {en='Screwdriver',skillchain={'Transfixion','Scission'}},
 [527] = {en='Smite of Rage',skillchain={'Detonation'}},
 [529] = {en='Bludgeon',skillchain={'Liquefaction'}},
 [539] = {en='Terror Touch',skillchain={'Compression','Reverberation'}},
 [540] = {en='Spinal Cleave',skillchain={'Scission','Detonation'}},
 [543] = {en='Mandibular Bite',skillchain={'Induration'}},
 [545] = {en='Sickle Slash',skillchain={'Compression'}},
 [551] = {en='Power Attack',skillchain={'Reverberation'}},
 [554] = {en='Death Scissors',skillchain={'Compression','Reverberation'}},
 [560] = {en='Frenetic Rip',skillchain={'Induration'}},
 [564] = {en='Body Slam',skillchain={'Impaction'}},
 [567] = {en='Helldive',skillchain={'Transfixion'}},
 [569] = {en='Jet Stream',skillchain={'Impaction'}},
 [577] = {en='Foot Kick',skillchain={'Detonation'}},
 [585] = {en='Ram Charge',skillchain={'Fragmentation'}},
 [587] = {en='Claw Cyclone',skillchain={'Scission'}},
 [589] = {en='Dimensional Death',skillchain={'Transfixion','Impaction'}},
 [594] = {en='Uppercut',skillchain={'Liquefaction','Impaction'}},
 [596] = {en='Pinecone Bomb',skillchain={'Liquefaction'}},
 [597] = {en='Sprout Smack',skillchain={'Reverberation'}},
 [599] = {en='Queasyshroom',skillchain={'Compression'}},
 [603] = {en='Wild Oats',skillchain={'Transfixion'}},
 [611] = {en='Disseverment',skillchain={'Distortion'}},
 [617] = {en='Vertical Cleave',skillchain={'Gravitation'}},
 [620] = {en='Battle Dance',skillchain={'Impaction'}},
 [622] = {en='Grand Slam',skillchain={'Induration'}},
 [623] = {en='Head Butt',skillchain={'Impaction'}},
 [628] = {en='Frypan',skillchain={'Impaction'}},
 [631] = {en='Hydro Shot',skillchain={'Reverberation'}},
 [638] = {en='Feather Storm',skillchain={'Transfixion'}},
 [640] = {en='Tail Slap',skillchain={'Reverberation'}},
 [641] = {en='Hysteric Barrage',skillchain={'Detonation'}},
 [643] = {en='Cannonball',skillchain={'Fusion'}},
 [650] = {en='Seedspray',skillchain={'Induration','Detonation'}},
 [652] = {en='Spiral Spin',skillchain={'Transfixion'}},
 [653] = {en='Asuran Claws',skillchain={'Liquefaction','Impaction'}},
 [654] = {en='Sub-zero Smash',skillchain={'Fragmentation'}},
 [665] = {en='Final Sting',skillchain={'Fusion'}},
 [666] = {en='Goblin Rush',skillchain={'Fusion','Impaction'}},
 [669] = {en='Whirl of Rage',skillchain={'Scission','Detonation'}},
 [670] = {en='Benthic Typhoon',skillchain={'Gravitation','Transfixion'}},
 [673] = {en='Quad. Continuum',skillchain={'Distortion','Scission'}},
 [677] = {en='Empty Thrash',skillchain={'Compression','Scission'}},
 [682] = {en='Delta Thrust',skillchain={'Liquefaction','Detonation'}},
 [688] = {en='Heavy Strike',skillchain={'Fragmentation','Transfixion'}},
 [692] = {en='Sudden Lunge',skillchain={'Detonation'}},
 [693] = {en='Quadrastrike',skillchain={'Liquefaction','Scission','Impaction'}},
 [697] = {en='Amorphic Spikes',skillchain={'Gravitation'}},
 [699] = {en='Barbed Crescent',skillchain={'Distortion','Scission'}},
 [704] = {en='Paralyzing Triad',skillchain={'Gravitation'}},
 [706] = {en='Glutinous Dart',skillchain={'Fragmentation'}},
 [709] = {en='Thrashing Assault',skillchain={'Fusion'}},
 [714] = {en='Sinker Drill',skillchain={'Gravitation','Reverberation'}},
 [723] = {en='Saurian Slide',skillchain={'Fragmentation','Distortion'}},
 [740] = {en='Tourbillion',skillchain={'Light','Fragmentation'}},
 [742] = {en='Bilgestorm',skillchain={'Darkness','Gravitation'}},
 [743] = {en='Bloodrake',skillchain={'Darkness','Distortion'}},
 [144] = {en='Fire',skillchain={'Liquefaction'}},
 [145] = {en='Fire II',skillchain={'Liquefaction'}},
 [146] = {en='Fire III',skillchain={'Liquefaction'}},
 [147] = {en='Fire IV',skillchain={'Liquefaction'}},
 [148] = {en='Fire V',skillchain={'Liquefaction'}},
 [149] = {en='Blizzard',skillchain={'Induration'}},
 [150] = {en='Blizzard II',skillchain={'Induration'}},
 [151] = {en='Blizzard III',skillchain={'Induration'}},
 [152] = {en='Blizzard IV',skillchain={'Induration'}},
 [153] = {en='Blizzard V',skillchain={'Induration'}},
 [154] = {en='Aero',skillchain={'Detonation'}},
 [155] = {en='Aero II',skillchain={'Detonation'}},
 [156] = {en='Aero III',skillchain={'Detonation'}},
 [157] = {en='Aero IV',skillchain={'Detonation'}},
 [158] = {en='Aero V',skillchain={'Detonation'}},
 [159] = {en='Stone',skillchain={'Scission'}},
 [160] = {en='Stone II',skillchain={'Scission'}},
 [161] = {en='Stone III',skillchain={'Scission'}},
 [162] = {en='Stone IV',skillchain={'Scission'}},
 [163] = {en='Stone V',skillchain={'Scission'}},
 [164] = {en='Thunder',skillchain={'Impaction'}},
 [165] = {en='Thunder II',skillchain={'Impaction'}},
 [166] = {en='Thunder III',skillchain={'Impaction'}},
 [167] = {en='Thunder IV',skillchain={'Impaction'}},
 [168] = {en='Thunder V',skillchain={'Impaction'}},
 [169] = {en='Water',skillchain={'Reverberation'}},
 [170] = {en='Water II',skillchain={'Reverberation'}},
 [171] = {en='Water III',skillchain={'Reverberation'}},
 [172] = {en='Water IV',skillchain={'Reverberation'}},
 [173] = {en='Water V',skillchain={'Reverberation'}},
 [278] = {en='Geohelix',skillchain={'Scission'},delay=5},
 [279] = {en='Hydrohelix',skillchain={'Reverberation'},delay=5},
 [280] = {en='Anemohelix',skillchain={'Detonation'},delay=5},
 [281] = {en='Pyrohelix',skillchain={'Liquefaction'},delay=5},
 [282] = {en='Cryohelix',skillchain={'Induration'},delay=5},
 [283] = {en='Ionohelix',skillchain={'Impaction'},delay=5},
 [284] = {en='Noctohelix',skillchain={'Compression'},delay=5},
 [285] = {en='Luminohelix',skillchain={'Transfixion'},delay=5},
 [503] = {en='Impact',skillchain={'Compression'}},
 [885] = {en='Geohelix II',skillchain={'Scission'},delay=5},
 [886] = {en='Hydrohelix II',skillchain={'Reverberation'},delay=5},
 [887] = {en='Anemohelix II',skillchain={'Detonation'},delay=5},
 [888] = {en='Pyrohelix II',skillchain={'Liquefaction'},delay=5},
 [889] = {en='Cryohelix II',skillchain={'Induration'},delay=5},
 [890] = {en='Ionohelix II',skillchain={'Impaction'},delay=5},
 [891] = {en='Noctohelix II',skillchain={'Compression'},delay=5},
 [892] = {en='Luminohelix II',skillchain={'Transfixion'},delay=5},
};

skills[13] = {
 [513] = {en='Poison Nails',skillchain={'Transfixion'},avatar='Carbuncle'},
 [521] = {en='Regal Scratch',skillchain={'Scission'},avatar='Cait Sith'},
 [528] = {en='Moonlit Charge',skillchain={'Compression'},avatar='Fenrir'},
 [529] = {en='Crescent Fang',skillchain={'Transfixion'},avatar='Fenrir'},
 [534] = {en='Eclipse Bite',skillchain={'Gravitation','Scission'},avatar='Fenrir'},
 [544] = {en='Punch',skillchain={'Liquefaction'},avatar='Ifrit'},
 [546] = {en='Burning Strike',skillchain={'Impaction'},avatar='Ifrit'},
 [547] = {en='Double Punch',skillchain={'Compression'},avatar='Ifrit'},
 [550] = {en='Flaming Crush',skillchain={'Fusion','Reverberation'},avatar='Ifrit'},
 [560] = {en='Rock Throw',skillchain={'Scission'},avatar='Titan'},
 [562] = {en='Rock Buster',skillchain={'Reverberation'},avatar='Titan'},
 [563] = {en='Megalith Throw',skillchain={'Induration'},avatar='Titan'},
 [566] = {en='Mountain Buster',skillchain={'Gravitation','Induration'},avatar='Titan'},
 [570] = {en='Crag Throw',skillchain={'Gravitation','Scission'},avatar='Titan'},
 [576] = {en='Barracuda Dive',skillchain={'Reverberation'},avatar='Leviathan'},
 [578] = {en='Tail Whip',skillchain={'Detonation'},avatar='Leviathan'},
 [582] = {en='Spinning Dive',skillchain={'Distortion','Detonation'},avatar='Leviathan'},
 [592] = {en='Claw',skillchain={'Detonation'},avatar='Garuda'},
 [598] = {en='Predator Claws',skillchain={'Fragmentation','Scission'},avatar='Garuda'},
 [608] = {en='Axe Kick',skillchain={'Induration'},avatar='Shiva'},
 [612] = {en='Double Slap',skillchain={'Scission'},avatar='Shiva'},
 [614] = {en='Rush',skillchain={'Distortion','Scission'},avatar='Shiva'},
 [624] = {en='Shock Strike',skillchain={'Impaction'},avatar='Ramuh'},
 [630] = {en='Chaotic Strike',skillchain={'Fragmentation','Transfixion'},avatar='Ramuh'},
 [634] = {en='Volt Strike',skillchain={'Fragmentation','Scission'},avatar='Ramuh'},
 [656] = {en='Camisado',skillchain={'Compression'},avatar='Diabolos'},
 [667] = {en='Blindside',skillchain={'Gravitation','Transfixion'},avatar='Diabolos'},
};

skills[11] = {
 [672] = {en='Foot Kick',skillchain={'Reverberation'}},
 [674] = {en='Whirl Claws',skillchain={'Impaction'}},
 [675] = {en='Head Butt',skillchain={'Detonation'}},
 [677] = {en='Wild Oats',skillchain={'Transfixion'}},
 [678] = {en='Leaf Dagger',skillchain={'Scission'}},
 [681] = {en='Razor Fang',skillchain={'Impaction'}},
 [682] = {en='Claw Cyclone',skillchain={'Scission'}},
 [683] = {en='Tail Blow',skillchain={'Impaction'}},
 [685] = {en='Blockhead',skillchain={'Reverberation'}},
 [686] = {en='Brain Crush',skillchain={'Liquefaction'}},
 [689] = {en='Lamb Chop',skillchain={'Impaction'}},
 [691] = {en='Sheep Charge',skillchain={'Reverberation'}},
 [695] = {en='Big Scissors',skillchain={'Scission'}},
 [698] = {en='Needleshot',skillchain={'Transfixion'}},
 [699] = {en='Random Needles',skillchain={'Darkness','Fragmentation'}},
 [700] = {en='Frogkick',skillchain={'Compression'}},
 [707] = {en='Power Attack',skillchain={'Reverberation'}},
 [709] = {en='Rhino Attack',skillchain={'Detonation'}},
 [717] = {en='Mandibular Bite',skillchain={'Detonation'}},
 [723] = {en='Nimble Snap',skillchain={'Impaction'}},
 [724] = {en='Cyclotail',skillchain={'Impaction'}},
 [726] = {en='Double Claw',skillchain={'Liquefaction'}},
 [727] = {en='Grapple',skillchain={'Reverberation'}},
 [728] = {en='Spinning Top',skillchain={'Impaction'}},
 [732] = {en='Suction',skillchain={'Compression'}},
 [736] = {en='Sudden Lunge',skillchain={'Impaction'}},
 [737] = {en='Spiral Spin',skillchain={'Scission'}},
 [743] = {en='Scythe Tail',skillchain={'Liquefaction'}},
 [744] = {en='Ripper Fang',skillchain={'Induration'}},
 [745] = {en='Chomp Rush',skillchain={'Darkness','Gravitation'}},
 [749] = {en='Back Heel',skillchain={'Reverberation'}},
 [753] = {en='Tortoise Stomp',skillchain={'Liquefaction'}},
 [756] = {en='Wing Slap',skillchain={'Gravitation','Liquefaction'}},
 [757] = {en='Beak Lunge',skillchain={'Scission'}},
 [759] = {en='Recoil Dive',skillchain={'Transfixion'}},
 [761] = {en='Sensilla Blades',skillchain={'Scission'}},
 [762] = {en='Tegmina Buffet',skillchain={'Distortion','Detonation'}},
 [764] = {en='Swooping Frenzy',skillchain={'Fusion','Reverberation'}},
 [767] = {en='Pentapeck',skillchain={'Light','Distortion'}},
 [772] = {en='Somersault',skillchain={'Compression'}},
 [791] = {en='Rhinowrecker',skillchain={'Fusion','Scission'}},
 [795] = {en='Crossthrash',skillchain={'Distortion','Detonation'}},
 [797] = {en='Hoof Volley',skillchain={'Fragmentation'}},
};

skills[14] = {
--Samurai
 [320] = {en='Konzen-ittai',skillchain={'Light','Darkness','Gravitation','Fragmentation','Distortion','Compression','Liquefaction','Induration','Reverberation','Scission'}},
--Dancer
 [209] = {en='Wild Flourish',skillchain={'Compression','Liquefaction','Induration','Reverberation','Scission'}},
};

skills.immanence = {
 [1] = {en='Fire',skillchain={'Liquefaction'}},
 [2] = {en='Ice',skillchain={'Induration'}},
 [3] = {en='Wind',skillchain={'Detonation'}},
 [4] = {en='Earth',skillchain={'Scission'}},
 [5] = {en='Lightning',skillchain={'Impaction'}},
 [6] = {en='Water',skillchain={'Reverberation'}},
 [7] = {en='Light',skillchain={'Transfixion'}},
 [8] = {en='Dark',skillchain={'Compression'}},
};

skills.pup = {
 [1940] = {en='Chimera Ripper',skillchain={'Induration','Detonation'}},
 [1941] = {en='String Clipper',skillchain={'Scission','Impaction'}},
 [1942] = {en='Arcuballista',skillchain={'Liquefaction','Transfixion'}},
 [1943] = {en='Slapstick',skillchain={'Reverberation','Impaction'}},
 [2065] = {en='Cannibal Blade',skillchain={'Compression','Reverberation'}},
 [2066] = {en='Daze',skillchain={'Transfixion'}},
 [2067] = {en='Knockout',skillchain={'Scission','Detonation'}},
 [2299] = {en='Bone Crusher',skillchain={'Fragmentation'}},
 [2300] = {en='Armor Piercer',skillchain={'Gravitation'}},
 [2301] = {en='Magic Mortar',skillchain={'Fusion'}},
 [2743] = {en='String Shredder',skillchain={'Distortion','Scission'}},
 [2744] = {en='Armor Shatterer',skillchain={'Fusion','Impaction'}},
};

return skills;
